### ISSUE TITLE
PelicuLatino

### ISSUE THREAD

**Issue by marcostux06** [danamag/stremio-addons-list#100]
### Addon Manifest URL

https://app.strem.io/shell-v4.4/#/addons/community/all?addon=https%3A%2F%2Fpeliculatino.herokuapp.com%2Fmanifest.json

### Addon Description

¡Películas en excelente calidad con audio latino!

### Language of Content

Spanish; Castilian (es-MX)

### Choose Labels

- [ ] anime
- [ ] asian drama
- [ ] bollywood
- [ ] cartoons
- [ ] debrid support
- [ ] http streams
- [ ] live tv
- [ ] metadata
- [ ] misc
- [X] movies
- [ ] music
- [ ] nsfw
- [ ] podcasts
- [ ] radios
- [ ] subtitles
- [ ] torrents
- [ ] tv shows
- [ ] video games

**Comment by danamag** [comment]
this is not the way to submit working addons, they need to end with /manifest.json
