### ISSUE TITLE
Addon Nameblank_issues_enabled: true

### ISSUE THREAD

**Issue by wqawalos** [danamag/stremio-addons-list#103]
### Addon Manifest URL

blank_issues_enabled: true

### Addon Description

blank_issues_enabled: true

### Language of Content

Greek (el-GR)

### Choose Labels

- [ ] anime
- [ ] asian drama
- [ ] bollywood
- [ ] cartoons
- [ ] debrid support
- [X] http streams
- [ ] live tv
- [ ] metadata
- [ ] misc
- [X] movies
- [ ] music
- [ ] nsfw
- [ ] podcasts
- [ ] radios
- [X] subtitles
- [ ] torrents
- [ ] tv shows
- [ ] video games

**Comment by danamag** [comment]
i don't know what this is, but it's not an addon, closing it
