### ISSUE TITLE
Addon Name

### ISSUE THREAD

**Issue by iiSnow01** [danamag/stremio-addons-list#104]
### Addon Manifest URL

https://addon.peario.xyz/manifest.json

### Language of Content

Arabic (ar-AE)

### Choose Labels

- [ ] anime
- [ ] asian drama
- [ ] bollywood
- [ ] cartoons
- [ ] debrid support
- [ ] http streams
- [ ] live tv
- [ ] metadata
- [ ] misc
- [ ] movies
- [ ] music
- [ ] nsfw
- [ ] podcasts
- [ ] radios
- [ ] subtitles
- [ ] torrents
- [ ] tv shows
- [ ] video games

**Comment by danamag** [comment]
duplicate
