### ISSUE TITLE
Addon Name

### ISSUE THREAD

**Issue by reifixolas2006** [danamag/stremio-addons-list#106]
### Addon Manifest URL

https://www.strem.io/s/movie/price-of-parenting-13271264

### Language of Content

French (fr-FR)

### Choose Labels

- [ ] anime
- [ ] asian drama
- [X] bollywood
- [ ] cartoons
- [ ] debrid support
- [ ] http streams
- [ ] live tv
- [ ] metadata
- [ ] misc
- [X] movies
- [ ] music
- [ ] nsfw
- [ ] podcasts
- [ ] radios
- [ ] subtitles
- [ ] torrents
- [ ] tv shows
- [ ] video games

**Comment by danamag** [comment]
i don't know what this is, but it's not an addon, closing it
