### ISSUE TITLE
Addon Name

### ISSUE THREAD

**Issue by Bebanr** [danamag/stremio-addons-list#108]
### Addon Manifest URL

http://127.0.0.1:11470

### Language of Content

Arabic (ar-SA)

### Choose Labels

- [X] anime
- [ ] asian drama
- [ ] bollywood
- [ ] cartoons
- [ ] debrid support
- [ ] http streams
- [ ] live tv
- [ ] metadata
- [ ] misc
- [X] movies
- [ ] music
- [ ] nsfw
- [ ] podcasts
- [ ] radios
- [X] subtitles
- [X] torrents
- [X] tv shows
- [ ] video games

**Comment by danamag** [comment]
i don't know what this is, but it's not an addon, closing it
