### ISSUE TITLE
movies123

### ISSUE THREAD

**Issue by jackwhoyou** [danamag/stremio-addons-list#109]
### Addon Manifest URL

https://ww1.123moviesfree.net/

### Language of Content

English (en-IE)

### Choose Labels

- [ ] anime
- [ ] asian drama
- [ ] bollywood
- [ ] cartoons
- [ ] debrid support
- [X] http streams
- [X] live tv
- [ ] metadata
- [ ] misc
- [X] movies
- [ ] music
- [ ] nsfw
- [ ] podcasts
- [ ] radios
- [ ] subtitles
- [X] torrents
- [X] tv shows
- [ ] video games

**Comment by danamag** [comment]
i don't know what this is, but it's not an addon, closing it
