### ISSUE TITLE
Himovies by dexter21767

### ISSUE THREAD

**Issue by dexter21767** [danamag/stremio-addons-list#111]
### Addon Manifest URL

https://2ecbbd610840-hi-movies.baby-beamup.club/manifest.json

### Addon Description

Addon for Streaming from Himovies by Dexter21767

### Language of Content

Multilingual (Default)

### Choose Labels

- [ ] anime
- [ ] asian drama
- [ ] bollywood
- [ ] cartoons
- [ ] debrid support
- [X] http streams
- [ ] live tv
- [X] metadata
- [ ] misc
- [X] movies
- [ ] music
- [ ] nsfw
- [ ] podcasts
- [ ] radios
- [ ] subtitles
- [ ] torrents
- [X] tv shows
- [ ] video games

**Comment by hsp1020** [comment]
1

**Comment by Hex34568** [comment]
yo dexter take a look here you wont regret it: https://github.com/dexter21767/cinestream/issues/5
