### ISSUE TITLE
Peerflix

### ISSUE THREAD

**Issue by Elcaponi** [danamag/stremio-addons-list#113]
### Addon Manifest URL

https://peerflix-235ac-default-rtdb.europe-west1.firebasedatabase.app/manifest.json

### Language of Content

None

### Choose Labels

- [ ] anime
- [ ] asian drama
- [ ] bollywood
- [ ] cartoons
- [ ] debrid support
- [ ] http streams
- [ ] live tv
- [ ] metadata
- [ ] misc
- [ ] movies
- [ ] music
- [ ] nsfw
- [ ] podcasts
- [ ] radios
- [ ] subtitles
- [ ] torrents
- [ ] tv shows
- [ ] video games

**Comment by danamag** [comment]
this is a duplicate
