### ISSUE TITLE
Youcam

### ISSUE THREAD

**Issue by oviiic** [danamag/stremio-addons-list#114]
### Addon Manifest URL

https://bitsearch.to/trending

### Addon Description

Engine torrent magnet 

### Language of Content

Multilingual (Default)

### Choose Labels

- [X] anime
- [ ] asian drama
- [X] bollywood
- [X] cartoons
- [X] debrid support
- [X] http streams
- [ ] live tv
- [ ] metadata
- [ ] misc
- [X] movies
- [X] music
- [ ] nsfw
- [ ] podcasts
- [ ] radios
- [ ] subtitles
- [X] torrents
- [ ] tv shows
- [ ] video games

**Comment by danamag** [comment]
i don't know what this is, but it's not an addon, closing it
