### ISSUE TITLE
Addon Name

### ISSUE THREAD

**Issue by Jackieryan885** [danamag/stremio-addons-list#117]
### Addon Manifest URL

ex.https//.addon.server.com/. manifest 

### Language of Content

English (en-US)

### Choose Labels

- [ ] anime
- [ ] asian drama
- [ ] bollywood
- [ ] cartoons
- [ ] debrid support
- [x] http streams
- [X] live tv
- [ ] metadata
- [ ] misc
- [X] movies
- [ ] music
- [ ] nsfw
- [ ] podcasts
- [ ] radios
- [X] subtitles
- [ ] torrents
- [X] tv shows
- [ ] video games

**Comment by Jackieryan885** [comment]
Can't get any servers

**Comment by danamag** [comment]
i don't know what this is, but it's not an addon, closing it
