### ISSUE TITLE
We cinema 

### ISSUE THREAD

**Issue by issmailherbad** [danamag/stremio-addons-list#118]
### Addon Manifest URL

https://weciima.makeup/

### Language of Content

Arabic (ar-SA)

### Choose Labels

- [ ] anime
- [ ] asian drama
- [ ] bollywood
- [ ] cartoons
- [ ] debrid support
- [ ] http streams
- [ ] live tv
- [ ] metadata
- [ ] misc
- [X] movies
- [ ] music
- [ ] nsfw
- [ ] podcasts
- [ ] radios
- [ ] subtitles
- [ ] torrents
- [ ] tv shows
- [ ] video games

**Comment by danamag** [comment]
i don't know what this is, but it's not an addon, closing it
