### ISSUE TITLE
kitsu

### ISSUE THREAD

**Issue by Helmantes** [danamag/stremio-addons-list#122]
### Addon Manifest URL

https://app.strem.io/shell-v4.4/#/addons/community/all?addon=https%3A%2F%2Fanime-kitsu.strem.fun%2Fmanifest.json

### Language of Content

None

### Choose Labels

- [X] anime
- [ ] asian drama
- [ ] bollywood
- [X] cartoons
- [ ] debrid support
- [ ] http streams
- [ ] live tv
- [ ] metadata
- [ ] misc
- [ ] movies
- [ ] music
- [ ] nsfw
- [ ] podcasts
- [ ] radios
- [ ] subtitles
- [X] torrents
- [X] tv shows
- [ ] video games

**Comment by danamag** [comment]
i don't know what this is, but it's not an addon, closing it
