### ISSUE TITLE
Addon Name

### ISSUE THREAD

**Issue by Umutakkopru** [danamag/stremio-addons-list#124]
### Addon Manifest URL

addon

### Addon Description

ssss

### Language of Content

Turkish (tr-TR)

### Choose Labels

- [ ] anime
- [ ] asian drama
- [ ] bollywood
- [ ] cartoons
- [ ] debrid support
- [ ] http streams
- [X] live tv
- [ ] metadata
- [ ] misc
- [X] movies
- [ ] music
- [ ] nsfw
- [ ] podcasts
- [ ] radios
- [X] subtitles
- [X] torrents
- [X] tv shows
- [ ] video games

**Comment by danamag** [comment]
i don't know what this is, but it's not an addon, closing it
