### ISSUE TITLE
TORRENTIO v0.0.12

### ISSUE THREAD

**Issue by ghost** [danamag/stremio-addons-list#125]
### Addon Manifest URL

https://torrentio.strem.fun/manifest.json

### Language of Content

None

### Choose Labels

- [ ] anime
- [ ] asian drama
- [ ] bollywood
- [ ] cartoons
- [ ] debrid support
- [ ] http streams
- [ ] live tv
- [ ] metadata
- [ ] misc
- [X] movies
- [ ] music
- [ ] nsfw
- [ ] podcasts
- [ ] radios
- [ ] subtitles
- [ ] torrents
- [X] tv shows
- [ ] video games

**Comment by danamag** [comment]
this addon was already submitted by someone else
