### ISSUE TITLE
alover007

### ISSUE THREAD

**Issue by alover007** [danamag/stremio-addons-list#126]
### Addon Manifest URL

ex. Http://addon.server.com/manifest.json

### Language of Content

Arabic (ar-SA)

### Choose Labels

- [X] anime
- [X] asian drama
- [ ] bollywood
- [X] cartoons
- [X] debrid support
- [X] http streams
- [X] live tv
- [X] metadata
- [ ] misc
- [X] movies
- [ ] music
- [X] nsfw
- [X] podcasts
- [ ] radios
- [X] subtitles
- [X] torrents
- [ ] tv shows
- [X] video games

**Comment by danamag** [comment]
i don't know what this is, but it's not an addon, closing it
