### ISSUE TITLE
قصة عشق

### ISSUE THREAD

**Issue by Mohemmad2023** [danamag/stremio-addons-list#127]
### Addon Manifest URL

https://ee.e3sk.net/

### Language of Content

Turkish (tr-TR)

### Choose Labels

- [x] anime
- [X] asian drama
- [x] bollywood
- [x] cartoons
- [x] debrid support
- [x] http streams
- [x] live tv
- [x] metadata
- [x] misc
- [x] movies
- [x] music
- [x] nsfw
- [x] podcasts
- [x] radios
- [x] subtitles
- [x] torrents
- [x] tv shows
- [x] video games

**Comment by danamag** [comment]
i don't know what this is, but it's not an addon, closing it
