### ISSUE TITLE
e3sk

### ISSUE THREAD

**Issue by Mohemmad2023** [danamag/stremio-addons-list#128]
### Addon Manifest URL

https://ee.e3sk.net/

### Language of Content

None

### Choose Labels

- [ ] anime
- [ ] asian drama
- [ ] bollywood
- [ ] cartoons
- [ ] debrid support
- [ ] http streams
- [ ] live tv
- [ ] metadata
- [ ] misc
- [ ] movies
- [ ] music
- [ ] nsfw
- [ ] podcasts
- [ ] radios
- [ ] subtitles
- [ ] torrents
- [X] tv shows
- [ ] video games

**Comment by danamag** [comment]
i don't know what this is, but it's not an addon, closing it
