### ISSUE TITLE
Torrentio

### ISSUE THREAD

**Issue by KingDonRush** [danamag/stremio-addons-list#129]
### Addon Manifest URL

stremio://torrentio.strem.fun/manifest.json

### Addon Description

Torrentio

### Language of Content

None

### Choose Labels

- [ ] anime
- [ ] asian drama
- [ ] bollywood
- [X] cartoons
- [ ] debrid support
- [ ] http streams
- [ ] live tv
- [ ] metadata
- [ ] misc
- [X] movies
- [ ] music
- [ ] nsfw
- [ ] podcasts
- [ ] radios
- [ ] subtitles
- [X] torrents
- [ ] tv shows
- [ ] video games

**Comment by danamag** [comment]
this addon is already submitted by someone else
