### ISSUE TITLE
appelettv.com

### ISSUE THREAD

**Issue by tomtomclub** [danamag/stremio-addons-list#131]
### Addon Manifest URL

https://iptv-tester close 

### Addon Description

spanish english vob tv

### Language of Content

Multilingual (Default)

### Choose Labels

- [ ] anime
- [ ] asian drama
- [ ] bollywood
- [ ] cartoons
- [ ] debrid support
- [ ] http streams
- [ ] live tv
- [ ] metadata
- [ ] misc
- [X] movies
- [ ] music
- [ ] nsfw
- [ ] podcasts
- [ ] radios
- [ ] subtitles
- [ ] torrents
- [X] tv shows
- [ ] video games

**Comment by danamag** [comment]
i don't know what this is, but it's not an addon, closing it
