### ISSUE TITLE
Nameonrender.com

### ISSUE THREAD

**Issue by tomtomclub** [danamag/stremio-addons-list#132]
### Addon Manifest URL

https://closed 

### Addon Description

.onrender.com English and Spanish para hablantes de español e ingles 

### Language of Content

None

### Choose Labels

- [ ] anime
- [ ] asian drama
- [ ] bollywood
- [ ] cartoons
- [ ] debrid support
- [ ] http streams
- [x] live tv
- [ ] metadata
- [ ] misc
- [ ] movies
- [ ] music
- [ ] nsfw
- [ ] podcasts
- [ ] radios
- [ ] subtitles
- [ ] torrents
- [ ] tv shows
- [ ] video games

**Comment by danamag** [comment]
i don't know what this is, but it's not an addon, closing it
