### ISSUE TITLE
tomtomclub world  stream sport & movie

### ISSUE THREAD

**Issue by tomtomclub** [danamag/stremio-addons-list#134]
### Addon Manifest URL

https://iptv closed!!

### Addon Description

Yeah foks. enjoy this sports movie and series stream 

### Language of Content

None

### Choose Labels

- [ ] anime
- [ ] asian drama
- [ ] bollywood
- [ ] cartoons
- [ ] debrid support
- [ ] http streams
- [X] live tv
- [ ] metadata
- [ ] misc
- [ ] movies
- [ ] music
- [ ] nsfw
- [ ] podcasts
- [ ] radios
- [ ] subtitles
- [ ] torrents
- [ ] tv shows
- [ ] video games

**Comment by danamag** [comment]
i don't know what this is, but it's not an addon, so i'm closing it
