### ISSUE TITLE
ℋ ✨ Premium-Griechisch ✨ 󠁴󠁭󠁢󠁿  Ỵ

### ISSUE THREAD

**Issue by mik25** [danamag/stremio-addons-list#135]
### Addon Manifest URL

https://hgreektvy.surge.sh/manifest.json

### Addon Description

Griechische Premium-Livestreams

### Language of Content

Greek (el-GR)

### Choose Labels

- [ ] anime
- [ ] asian drama
- [ ] bollywood
- [ ] cartoons
- [ ] debrid support
- [X] http streams
- [X] live tv
- [ ] metadata
- [ ] misc
- [ ] movies
- [ ] music
- [ ] nsfw
- [ ] podcasts
- [ ] radios
- [ ] subtitles
- [ ] torrents
- [ ] tv shows
- [ ] video games

**Comment by fanis24** [comment]
I added the addon and although at the beginning it was working without any issue now is not playing at all. 

I unistall and install it once more and is not working
