### ISSUE TITLE
Free stuff

### ISSUE THREAD

**Issue by EliSar23** [danamag/stremio-addons-list#136]
### Addon Manifest URL

Streemio/manifest.json

### Addon Description

I don't know what to write

### Language of Content

English (en-US)

### Choose Labels

- [ ] anime
- [ ] asian drama
- [ ] bollywood
- [ ] cartoons
- [ ] debrid support
- [ ] http streams
- [ ] live tv
- [ ] metadata
- [ ] misc
- [X] movies
- [ ] music
- [ ] nsfw
- [ ] podcasts
- [ ] radios
- [ ] subtitles
- [ ] torrents
- [ ] tv shows
- [ ] video games

**Comment by Elcaponi** [comment]
> ### Addon Manifest URL
> 
> Streemio/manifest.json
> 
> ### Addon Description
> 
> I don't know what to write
> 
> 
> ### Language of Content
> 
> English (en-US)
> 
> ### Choose Labels
> 
> - [ ] anime
> - [ ] asian drama
> - [ ] bollywood
> - [ ] cartoons
> - [ ] debrid support
> - [ ] http streams
> - [ ] live tv
> - [ ] metadata
> - [ ] misc
> - [X] movies
> - [ ] music
> - [ ] nsfw
> - [ ] podcasts
> - [ ] radios
> - [ ] subtitles
> - [ ] torrents
> - [ ] tv shows
> - [ ] video games

**Comment by danamag** [comment]
i don't know what this is, but it's not an addon, closing
