### ISSUE TITLE
HarryPotterAddon

### ISSUE THREAD

**Issue by zaik2007** [danamag/stremio-addons-list#139]
### Addon Manifest URL

https://flixhq.ru/manifest.json

### Addon Description

FlixHQ

### Language of Content

None

### Choose Labels

- [ ] anime
- [ ] asian drama
- [ ] bollywood
- [ ] cartoons
- [ ] debrid support
- [ ] http streams
- [ ] live tv
- [ ] metadata
- [ ] misc
- [X] movies
- [ ] music
- [ ] nsfw
- [ ] podcasts
- [ ] radios
- [ ] subtitles
- [ ] torrents
- [X] tv shows
- [ ] video games

**Comment by danamag** [comment]
i don't know what this is, but it's not an addon, closing
