### ISSUE TITLE
Anime Catalogs

### ISSUE THREAD

**Issue by danamag** [danamag/stremio-addons-list#147]
### Addon Manifest URL

https://1fe84bc728af-stremio-anime-catalogs.baby-beamup.club/manifest.json

### Addon Description

Stremio catalogs for anime from: MyAnimeList, AniDB, AniList, Kitsu. Also supports filtering by dubbed and optional setting to use Rating Posters from RPDB.

### Language of Content

None

### Choose Labels

- [X] anime
- [ ] asian drama
- [ ] bollywood
- [ ] cartoons
- [ ] debrid support
- [ ] http streams
- [ ] live tv
- [X] metadata
- [ ] misc
- [ ] movies
- [ ] music
- [ ] nsfw
- [ ] podcasts
- [ ] radios
- [ ] subtitles
- [ ] torrents
- [ ] tv shows
- [ ] video games

**Comment by lerd2805** [comment]
https://1fe84bc728af-stremio-anime-catalogs.baby-beamup.club/configure not working, i cant install addon anymore.

**Comment by TheAymen** [comment]
It still works fine for me. The only issue is that the seasonal anime (Trending/Airing catalogs) do not update as often as they should. 

Overall a good Kitsu-based add-on though, because it works well with Animeo Anilist tracking.
