### ISSUE TITLE
Tudublado 🇧🇷

### ISSUE THREAD

**Issue by italodeandra** [danamag/stremio-addons-list#150]
### Addon Manifest URL

https://tudublado.com.br/manifest.json

### Addon Description

Movies and TV shows dubbed in brazilian portuguese.

Movies and episodes that you open and is not available yet are added to our upload queue.

We also have some movies/shows/animes with original audio.

---

Filmes e séries dublados em português brasileiro.

Filmes e episódios que você abre e ainda não está disponível são adicionados na nossa fila de upload.

Nós também temos alguns filmes/séries/animes com áudio original.

### Language of Content

Brazilian Portuguese (pt-BR)

### Choose Labels

- [X] anime
- [ ] asian drama
- [ ] bollywood
- [x] cartoons
- [ ] debrid support
- [X] http streams
- [ ] live tv
- [ ] metadata
- [ ] misc
- [X] movies
- [ ] music
- [ ] nsfw
- [ ] podcasts
- [ ] radios
- [x] subtitles
- [ ] torrents
- [X] tv shows
- [ ] video games

**Comment by RafaelDilva** [comment]
Falta REDECANAS site

**Comment by italodeandra** [comment]
> Falta REDECANAS site

Olá Rafael, não entendi o seu comentário. Pode me explicar, por favor?

**Comment by mekclaud** [comment]
olá como faz para instalar?

**Comment by Casssy243** [comment]
Como faz para colocar no stremio??

**Comment by cutiebonn** [comment]
morreu faz 10 dias, arruma issod ai
