### ISSUE TITLE
MyCima by LazyDev

### ISSUE THREAD

**Issue by A-AllaaEddine** [danamag/stremio-addons-list#16]
### Addon Manifest URL

https://3bf59d9737bf-mycimaaddonbylazydzv.baby-beamup.club/manifest.json

### Addon Description

addon for streaming from mycima.fun !

### Language of Content

Arabic (ar-DZ)

**Comment by danamag** [comment]
thanks for the submit! this addon seems broken for me though, only the catalogs work.. but metadata and streams give errors

**Comment by A-AllaaEddine** [comment]
thanks for the info, i'll work on a fix asap!

**Comment by A-AllaaEddine** [comment]
i did fixed the issue, everthing seems to be working just fine now.

> thanks for the submit! this addon seems broken for me though, only the catalogs work.. but metadata and streams give errors

**Comment by challou77** [comment]
https://goku.to/home

**Comment by challou77** [comment]
http://www.streamlord.com/index.html

**Comment by Ramghh** [comment]
It doesn't work. I'd appreciate it if it got fixed

**Comment by Ziad8a** [comment]
2023 not working, hope the problem is solved
Heaps, tuktukcima, FaselHD WECIMA, I hope to add it as soon as possible, thank you.

**Comment by Zabizabizabi** [comment]
salam please kho fix it befor ramadan 
thanks for the effort
