### ISSUE TITLE
Cinestream by dexter21767

### ISSUE THREAD

**Issue by dexter21767** [danamag/stremio-addons-list#171]
### Addon Manifest URL

https://2ecbbd610840-cinestream.baby-beamup.club/manifest.json

### Addon Description

fast stream over https with multiple subtitles directly from cinemeta, by Dexter21767

### Language of Content

None

### Choose Labels

- [ ] anime
- [ ] asian drama
- [ ] bollywood
- [ ] cartoons
- [ ] debrid support
- [X] http streams
- [ ] live tv
- [ ] metadata
- [ ] misc
- [X] movies
- [ ] music
- [ ] nsfw
- [ ] podcasts
- [ ] radios
- [ ] subtitles
- [ ] torrents
- [X] tv shows
- [ ] video games

**Comment by Glorfindel9900** [comment]
Find something to watch movies in Spanish 😅

**Comment by Glorfindel9900** [comment]
They could also have content in Latin Spanish, please.

**Comment by Glorfindel9900** [comment]
Could you consider adding content in Spanish, please 🙏🏻, Thank you so much.
