### ISSUE TITLE
StreamAR by dexter21767

### ISSUE THREAD

**Issue by dexter21767** [danamag/stremio-addons-list#172]
### Addon Manifest URL

https://2ecbbd610840-stremio-ar.baby-beamup.club/manifest.json

### Addon Description

Addon for Streaming from Arabic websites by Dexter21767, Currently supports Akwam, Wecima.

### Language of Content

Arabic (ar-DZ)

### Choose Labels

- [X] anime
- [X] asian drama
- [X] bollywood
- [ ] cartoons
- [ ] debrid support
- [X] http streams
- [ ] live tv
- [ ] metadata
- [ ] misc
- [X] movies
- [ ] music
- [ ] nsfw
- [ ] podcasts
- [ ] radios
- [ ] subtitles
- [ ] torrents
- [X] tv shows
- [ ] video games

**Comment by sultanmonsur** [comment]
The link is not available to stream Asian movies.
A movie does not provide torrent links.
What is the reason for that?

**Comment by Ramghh** [comment]
The addon stopped working sometime ago but now it is working great.

**Comment by elmezouri** [comment]
Add
 https://www.faselhd.vip/

**Comment by Tkampsus23** [comment]
Good job 🤝

**Comment by mode0192** [comment]
Add arabseed.show it will be great and it is better than wecima and akwam.
Many thanks
