### ISSUE TITLE
ℋ ✨ DMW LIVE SPORTS ✨ 󠁴󠁭󠁢󠁿 Ỵ

### ISSUE THREAD

**Issue by mik25** [danamag/stremio-addons-list#182]
### Addon Manifest URL

https://flare-sport.pages.dev/manifest.json

### Addon Description

BEIN INTL MOVISTAR ESP and OTHER MIXED WORLD SPORTS

### Language of Content

None

### Choose Labels

- [ ] anime
- [ ] asian drama
- [ ] bollywood
- [ ] cartoons
- [ ] debrid support
- [ ] http streams
- [X] live tv
- [ ] metadata
- [ ] misc
- [ ] movies
- [ ] music
- [ ] nsfw
- [ ] podcasts
- [ ] radios
- [ ] subtitles
- [ ] torrents
- [ ] tv shows
- [ ] video games

**Comment by placidcasual98** [comment]
I have come across one problem that I have with dmw when I select my stream. It's fine the first one that I've stream.But if I press back out and then select another one that will probably work but then the next one the app gets an error and also the app might crash. but I've been looking at it and it seems to be that when you come out when you press back it doesn't actually stop that stream and it's still kind of playing in the background somehow. I've looked at my network activity for that device and the download speed stays the same when you back out .You don't hear it or see it but overloads the app and then it eventually crashes. I think if the stream had an actual stop button this would negate this problem. I don't know where I would mention this or who I would mention this too, but any help would be great.

**Comment by CoolCooler0** [comment]
This is a great addon. I was looking for a sport add-on for Streamio for awhile. It has all the channels I need. Thank you and I hope it will be maintained and updated.

**Comment by Stofcri** [comment]
DMW LIVE SPORTS Doesn’t seems to work in Uk 26 august 2023 19:00

**Comment by placidcasual98** [comment]
Probably because you're blocked. You might also need a VPN as well. Depends
on your provider.

**Comment by Stofcri** [comment]
> Probably because you're blocked. You might also need a VPN as well. Depends on your provider.
> […](#)

Thanks for the reply. I appreciate the follow up. It was working fine for the past few days. I also tried with a vpn still no luck. Thanks.

**Comment by Stofcri** [comment]
After trying a few times while on VPN to the US, it looks like it worked for a few channel that I have used the most. Thanks.

**Comment by Stofcri** [comment]
Just 

> After trying a few times while on VPN to the US, it looks like it worked for a few channel that I have used the most. Thanks.

Update: only previously watched channels have links and don’t necessary load video. Tried on 2 different accounts, fresh install. Let’s hope it gets fixed. I love the add on, thanks for the great work!

**Comment by CoolCooler0** [comment]
After the stremio update a lot of Sport streams doesn't work anymore.

**Comment by Stofcri** [comment]
> After the stremio update a lot of Sport streams doesn't work anymore.

Hi. Thanks for the follow up. Have you tried the old stremio version? Thanks.

**Comment by placidcasual98** [comment]
New stremio up out will this be update to work with it

**Comment by CoolCooler0** [comment]
There is no more content on this addon. Please fix

**Comment by placidcasual98** [comment]
The UK one seems to be working again

**Comment by CoolCooler0** [comment]
I cant find it on the list anymore. How can I add it again to Streamio?

**Comment by CoolCooler0** [comment]
When i search for the add on it doesnt show up anymore

**Comment by placidcasual98** [comment]
I don't think you understand me. I had already installed and never
uninstalled it. It's just in my list of installed apps. Can't find it on
the thing. I can't help you. I don't know why..

**Comment by CoolCooler0** [comment]
No problem. I understand.
