### ISSUE TITLE
ℋ  STREAMING SERVICES  Ỵ

### ISSUE THREAD

**Issue by mik25** [danamag/stremio-addons-list#185]
### Addon Manifest URL

https://hsservicesy.surge.sh/manifest.json

### Addon Description

Various Web and App Streaming Services

### Language of Content

None

### Choose Labels

- [X] anime
- [ ] asian drama
- [ ] bollywood
- [X] cartoons
- [ ] debrid support
- [ ] http streams
- [X] live tv
- [ ] metadata
- [ ] misc
- [X] movies
- [X] music
- [ ] nsfw
- [ ] podcasts
- [ ] radios
- [ ] subtitles
- [ ] torrents
- [X] tv shows
- [X] video games

**Comment by Glorfindel9900** [comment]
I would have loved them to add channels from more Latin American countries 😅

**Comment by Rooossssaaaa** [comment]
Kan er ook Nederlandse ondertiteling bij komen
