### ISSUE TITLE
ℋ ✨ Groetjes uit nederland ✨ 󠁴󠁭󠁢󠁿 Ỵ

### ISSUE THREAD

**Issue by mikmc55** [danamag/stremio-addons-list#189]
### Addon Manifest URL

https://hnly.surge.sh/manifest.json

### Addon Description

Nederlandse Netwerken, Sport en Entertainment

### Language of Content

None

### Choose Labels

- [ ] anime
- [ ] asian drama
- [ ] bollywood
- [ ] cartoons
- [ ] debrid support
- [ ] http streams
- [X] live tv
- [ ] metadata
- [ ] misc
- [ ] movies
- [ ] music
- [ ] nsfw
- [ ] podcasts
- [ ] radios
- [ ] subtitles
- [ ] torrents
- [ ] tv shows
- [ ] video games

**Comment by challou77** [comment]
hi ga je nog die kanalen herstellen,? of is het afgelopen met het streamen .grts ben
