### ISSUE TITLE
Media Fusion

### ISSUE THREAD

**Issue by mhdzumair** [danamag/stremio-addons-list#227]
### Addon Manifest URL

https://mediafusion.fun/manifest.json

### Addon Description

Watch Tamil, Hindi, Malayalam, Kannada, English, and dubbed movies & series with the Media Fusion add-on. Source: https://github.com/mhdzumair/MediaFusion

### Language of Content

Multilingual (Default)

### Choose Labels

- [ ] anime
- [X] asian drama
- [X] bollywood
- [ ] cartoons
- [X] debrid support
- [X] http streams
- [X] live tv
- [X] metadata
- [ ] misc
- [X] movies
- [ ] music
- [ ] nsfw
- [ ] podcasts
- [ ] radios
- [ ] subtitles
- [X] torrents
- [X] tv shows
- [ ] video games

**Comment by buntyvemula** [comment]
not getting content. Installed mutilple time but no content

**Comment by mhdzumair** [comment]
> not getting content. Installed mutilple time but no content

If you need any help or suggestion, Open the issues in https://github.com/mhdzumair/MediaFusion/issues. 
Btw, I have introduced rate limiting as below. 
> General API limit: 50 / 1 min
Catalog endpoint: 150 / 5 min
Stream endpoint: 10 / 1 hour
Streaming provider endpoint and poster endpoints are excluded from rate limitation since its a real user's usage endpoints.

Maybe you're affected from this?
