### ISSUE TITLE
Superflix

### ISSUE THREAD

**Issue by Aisss0** [danamag/stremio-addons-list#241]
### Addon Manifest URL

https://23dfbfad8cb2-stremio-addon-superflix.baby-beamup.club/manifest.json

### Addon Description

Stream online from multiple 3rd party meta-sources

### Language of Content

None

### Choose Labels

- [ ] anime
- [X] asian drama
- [X] bollywood
- [ ] cartoons
- [ ] debrid support
- [X] http streams
- [ ] live tv
- [ ] metadata
- [ ] misc
- [X] movies
- [ ] music
- [ ] nsfw
- [ ] podcasts
- [ ] radios
- [ ] subtitles
- [ ] torrents
- [X] tv shows
- [ ] video games

**Comment by RafaelDilva** [comment]
Put https://redecanais.la/index.html 🙏🏻🙏🏻

**Comment by tomtomclub** [comment]
Its not working any more

**Comment by frankycolumbo007** [comment]
Re-installed multiple times and continue to get "no links found"
Understand this is a new addon, will wait until the bugs are sorted out before trying again

**Comment by frankycolumbo007** [comment]
Was finally able to get links after multiple re-installs but noticed they seemed to be 720 quality at best, also there was a loading delay and Stremio crashing issues other than that it's great 🥴

**Comment by hotice52** [comment]
Is it possible to include Italian sites?

**Comment by hotice52** [comment]
Is it possible to include Italian sites?

**Comment by marcojoao** [comment]
you can add this one if you want: https://pobretv.limo/inicio/

**Comment by Popol11** [comment]
Using superflix addon its safe for Germany?

**Comment by MrSick0ff** [comment]
> Using superflix addon its safe for Germany?

You need VPN for everything. But should be safe

**Comment by joepnxsun** [comment]
sadly this addon is a hit and miss. every other day it has links and it doesn't provide the same movie/series for the link. i guess this addon is busted ever since it came out.

**Comment by Dragas1** [comment]
Hey,
Would it be possible to add more links to this addon?
There are not many series included in this add on, and i thought if its possible to assist with adding more to it?
Im using it via stremio.

**Comment by tkien931** [comment]
This is dead btw

**Comment by realgooseman** [comment]
Doesn't work, no working HTTP stream plugin for Stremio. Too bad...

**Comment by Djlilyazii** [comment]
this add on is dead btw

**Comment by sleeyax** [comment]
After careful review we've concluded that this addon no longer fits our [Addon submission guidelines](https://github.com/danamag/stremio-addons-list?tab=readme-ov-file#addon-submission-rules) due to potentially malicious ads being served on the configuration page. 

Please either move to a trustworthy ad network or switch to a donation-based model before submitting your addon again. Thanks for understanding.

**Comment by Shazly8** [comment]
Is superflix will be back or not
