### ISSUE TITLE
THЄ ѪАGЇC PГЦ$ TѴ

### ISSUE THREAD

**Issue by FiefNoodles** [danamag/stremio-addons-list#246]
### Addon Manifest URL

https://magic-live.pages.dev/manifest.json

### Addon Description

WORLD STREAMS by | Ⓝⓞ๏Ⓓ𝕃έᔕ

### Language of Content

None

### Choose Labels

- [ ] anime
- [ ] asian drama
- [ ] bollywood
- [ ] cartoons
- [ ] debrid support
- [ ] http streams
- [X] live tv
- [ ] metadata
- [ ] misc
- [ ] movies
- [ ] music
- [ ] nsfw
- [ ] podcasts
- [ ] radios
- [ ] subtitles
- [ ] torrents
- [ ] tv shows
- [ ] video games

**Comment by Mahmoud23go** [comment]
> ### Addon Manifest URL
> 
> https://magic-live.pages.dev/manifest.json
> 
> ### Addon Description
> 
> WORLD STREAMS by | Ⓝⓞ๏Ⓓ𝕃έᔕ
> 
> ### Language of Content
> 
> None
> 
> ### Choose Labels
> 
> - [ ] anime
> - [ ] asian drama
> - [ ] bollywood
> - [ ] cartoons
> - [ ] debrid support
> - [ ] http streams
> - [X] live tv
> - [ ] metadata
> - [ ] misc
> - [ ] movies
> - [ ] music
> - [ ] nsfw
> - [ ] podcasts
> - [ ] radios
> - [ ] subtitles
> - [ ] torrents
> - [ ] tv shows
> - [ ] video games

**Comment by Mahmoud23go** [comment]
> > ### Addon Manifest URL
> > 
> > https://magic-live.pages.dev/manifest.json
> > 
> > ### Addon Description
> > 
> > WORLD STREAMS by | Ⓝⓞ๏Ⓓ𝕃έᔕ
> > 
> > ### Language of Content
> > 
> > None
> > 
> > ### Choose Labels
> > 
> > - [ ] anime
> > - [ ] asian drama
> > - [ ] bollywood
> > - [ ] cartoons
> > - [ ] debrid support
> > - [ ] http streams
> > - [X] live tv
> > - [ ] metadata
> > - [ ] misc
> > - [ ] movies
> > - [ ] music
> > - [ ] nsfw
> > - [ ] podcasts
> > - [ ] radios
> > - [ ] subtitles
> > - [ ] torrents
> > - [ ] tv shows
> > - [ ] video games
> 
>
