### ISSUE TITLE
乁(⌐■ ʖ■)ㄏ NOODLES TV II

### ISSUE THREAD

**Issue by mikmcdanbyeee55** [danamag/stremio-addons-list#256]
### Addon Manifest URL

https://tvnoodles.surge.sh/manifest.json

### Addon Description

MIXED IPTV by | Ⓝⓞ๏Ⓓ𝕃έᔕ

### Language of Content

None

### Choose Labels

- [ ] anime
- [ ] asian drama
- [ ] bollywood
- [ ] cartoons
- [ ] debrid support
- [ ] http streams
- [X] live tv
- [ ] metadata
- [ ] misc
- [ ] movies
- [ ] music
- [ ] nsfw
- [ ] podcasts
- [ ] radios
- [ ] subtitles
- [ ] torrents
- [ ] tv shows
- [ ] video games

**Comment by frmariam** [comment]
error_code_io_bad_http_status for every channel I tried

**Comment by frmariam** [comment]
stremio app updated.
Portugal channels either have no streams or give error_code_io_bad_http_status
