### ISSUE TITLE
Your IPTV

### ISSUE THREAD

**Issue by gorlev** [danamag/stremio-addons-list#27]
### Addon Manifest URL

https://5a0d1888fa64-your-iptv.baby-beamup.club/manifest.json

### Addon Description

This addon brings all the _Live Streams_, _VOD streams_ and _Series_ from your IPTV subscription to your Stremio using Xtream API.

**Comment by mik25** [comment]
useful addition to stremio

**Comment by danamag** [comment]
@gorlev does this addon need a "M3U Playlist URL"? I think so, and "IPTV URL" is very confusing if that is the case, the addon description is very confusing too

**Comment by gorlev** [comment]
> @gorlev does this addon need a "M3U Playlist URL"? I think so, and "IPTV URL" is very confusing if that is the case, the addon description is very confusing too

Yes. It actually parses the username and password from the M3U playlist URL and make requests to the XtreamAPI with the credentials. By this way it can show all the series, VOD and LiveTV streams. I need to update the description and maybe improve the configuration page. I will work on this when I have time.

**Comment by rodimus75** [comment]
Any IPTV for free? Can anyone share?

**Comment by papajo-r** [comment]
I dont have a subscription and just want to add these FREE channels that are available on my country (so that I just have stremio and my parents do not need to go anywhere else in order to watch free local TV for news etc) 

this is the m3u url https://lists.iptvgenerate.com/mylist/0d2b338c-2cdf-4414-9a39-2ee42c9a71e6.m3u it provides the file with the IPs/links for each channel etc..  

But I cant use that because they are not a subscription so they dont have username and password... can't you make it so that free stuff without username and pass can be added to stremio as well?

**Comment by belyoni** [comment]
I paid for iptv but it doesn't work

**Comment by Stofcri** [comment]
I set up the add on fine 2days ago, but unable to install since last night. Any idea when the install process can be restored. Looks like the add on is offline right now. Thanks.

**Comment by Stofcri** [comment]
All working now. Thank you for the great work.

**Comment by vincemtl** [comment]
I get failed to fetch error, from either installing from the addon or from the json link

**Comment by leele2** [comment]
not working for me either, can't install the addon

**Comment by DriicooDC** [comment]
A algum tempo não consigo instalar o addon, sempre aparece um erro "ERR_OPENING_MEDIA" "Failed to fetch"

Alguém sabe do que se trata? Alguma ideia de como corrigir?

**Comment by outeiro13** [comment]
Olá também não estou conseguindo adicionar a lista paga ele da erro e não carrega se puder arrumar o app agradeço.

**Comment by Inqusitor19** [comment]
Doesn't work with my Xtream login error 504 could not fetch, Try something else.

**Comment by cransono** [comment]
How to I install this addon? Tried it several times and failed. Is there somewhere this addon is hosted so that I can download?

**Comment by alanmilinovic** [comment]
Addon is dead.

**Comment by ApenasGabs** [comment]
@gorlev what can I do to fix this addon? I can fix this if you don't have much time to do it.
