### ISSUE TITLE
Shluflix | ElfHosted

### ISSUE THREAD

**Issue by brianamit2017** [danamag/stremio-addons-list#273]
### Addon Manifest URL

https://shluflix.elfhosted.com/manifest.json

### Addon Description

Very simple addon that return a single http stream you can watch! 
The addons wraps the npm package created and used by movie-web https://github.com/movie-web/providers and return the result it gives.

### Language of Content

Multilingual (Default)

### Choose Labels

- [ ] anime
- [ ] asian drama
- [ ] bollywood
- [ ] cartoons
- [ ] debrid support
- [X] http streams
- [ ] live tv
- [ ] metadata
- [ ] misc
- [X] movies
- [ ] music
- [ ] nsfw
- [ ] podcasts
- [ ] radios
- [ ] subtitles
- [ ] torrents
- [X] tv shows
- [ ] video games

**Comment by megadrive** [comment]
I'd love for this to report the streams as highest to lowest quality.

**Comment by realgooseman** [comment]
Version 1.1.1 doesn't work and only shows one source without details: goojara.

Now that movie-web's repo is gone, will this plugin still get updated or are any hopes for working HTPP streams on Stremio dead ?
