### ISSUE TITLE
[UFO]Subscene - Reborn

### ISSUE THREAD

**Issue by Vance-ng-vn** [danamag/stremio-addons-list#298]
### Addon Manifest URL

https://subscene.stremio.homes/manifest.json

### Addon Description

Unofficial addon for getting the subtitles from Subscene.

### Language of Content

Multilingual (Default)

### Choose Labels

- [ ] anime
- [ ] asian drama
- [ ] bollywood
- [ ] cartoons
- [ ] debrid support
- [ ] http streams
- [ ] live tv
- [ ] metadata
- [ ] misc
- [ ] movies
- [ ] music
- [ ] nsfw
- [ ] podcasts
- [ ] radios
- [X] subtitles
- [ ] torrents
- [ ] tv shows
- [ ] video games

**Comment by tomtomclub** [comment]
Thanks you Very happy with it

**Comment by Mrnomad2150** [comment]
Hi, why ban for persian people? That's realy unkind💔

**Comment by Vance-ng-vn** [comment]
> Hi, why ban for persian people? That's realy unkind💔

Huh. Why do u saying that...?

**Comment by Vance-ng-vn** [comment]
Subscene.com is closed...

**Comment by Mrnomad2150** [comment]
I tried to install it before the site was closed, but I got an error.... nginx  403 forbidden

**Comment by Mrnomad2150** [comment]
From two months ago until now

**Comment by Mrnomad2150** [comment]
![Uploading Screenshot_2024-05-08-23-25-07-216_com.android.chrome.jpg…]()

**Comment by tomtomclub** [comment]
Same here The free host stops if it gets too much data and has nothing to do with Iran. I live in the Netherlands and it no longer works there

**Comment by Vance-ng-vn** [comment]
> Same here The free host stops if it gets too much data and has nothing to do with Iran. I live in the Netherlands and it no longer works there

Subscene is Closed bro ~~

**Comment by TwilightMercy** [comment]
Hi @Vance-ng-vn,

I want to implement similar addon to subscene.best website for Kodi,
Is it you for you to share here/privately, your code so I can translate it to python implementation?

Thank you

**Comment by Vance-ng-vn** [comment]
> Hi @Vance-ng-vn,
> 
> I want to implement similar addon to subscene.best website for Kodi, Is it you for you to share here/privately, your code so I can translate it to python implementation?
> 
> Thank you

Hi, there are many differences between Stremio and Kodi. Stremio addons are designed for 1000-10000 users, and they do not significantly increase requests to the Subscene website because they use a data storage database. Kodi is designed for single-user operation. Therefore, it's not possible to convert a Stremio addon to Kodi.

**Comment by TwilightMercy** [comment]
> Hi, there are many differences between Stremio and Kodi. Stremio addons are designed for 1000-10000 users, and they do not significantly increase requests to the Subscene website because they use a data storage database. Kodi is designed for single-user operation. Therefore, it's not possible to convert a Stremio addon to Kodi.

Thank you for the reply,
I know the addons architecture difference between Kodi and Stremio,

What I meant by "converting" your addon into python implementation is only for the Subscene.best website itself: searching for movie/tv show, extracing the subtitles from the HTML, etc. 
Not the other parts : )

Twilight

**Comment by tomtomclub** [comment]
Unfortunately that redirect issue no longer works

**Comment by TwilightMercy** [comment]
https://subscene.cam/

**Comment by tomtomclub** [comment]
thank you
