### ISSUE TITLE
[UFO]OpenSubtitles v3 Plus

### ISSUE THREAD

**Issue by Vance-ng-vn** [danamag/stremio-addons-list#299]
### Addon Manifest URL

https://opensubtitles.stremio.homes/manifest.json

### Language of Content

None

### Choose Labels

- [ ] anime
- [ ] asian drama
- [ ] bollywood
- [ ] cartoons
- [ ] debrid support
- [ ] http streams
- [ ] live tv
- [ ] metadata
- [ ] misc
- [ ] movies
- [ ] music
- [ ] nsfw
- [ ] podcasts
- [ ] radios
- [X] subtitles
- [ ] torrents
- [ ] tv shows
- [ ] video games

**Comment by notNSANE** [comment]
Please change the name to actually include a "Plus" or just change  the name, there are already other 2 official  subtitles named the exact same way

**Comment by notNSANE** [comment]
I think this only works for movies.

**Comment by Vance-ng-vn** [comment]
> I think this only works for movies.

Its working for movie, series, and some kitsu anime
(The IMDB meta data)

**Comment by tomtomclub** [comment]
Work well thank you

**Comment by enko2974** [comment]
2 days the addon doesnt work like before,it finds the subtitles bud doesnt display them,what coud be the problem,thanks

**Comment by Vance-ng-vn** [comment]
> 2 days the addon doesnt work like before,it finds the subtitles bud doesnt display them,what coud be the problem,thanks

This addon has simply been moved to a new paid VPS server. There some complaints that EDGE warns the website as a virus, and the website is also blocked in some countries (because it's shared hosting).

**Comment by enko2974** [comment]
Doesnt work,error

**Comment by sleeyax** [comment]
We have determined that your addon is potentially malicious and therefore we removed it from the catalog. Please comment if this is a mistake.

**Comment by Vance-ng-vn** [comment]
> We have determined that your addon is potentially malicious and therefore we removed it from the catalog. Please comment if this is a mistake.

Hi,

I am currently using two ad providers, Adsterra.com and Push.house, and there are no other suspicious scripts on the landing page!

Therefore, I would like to know the reason why this addon is considered harmful so that I can fix it!

Thank you!

**Comment by sleeyax** [comment]
@Vance-ng-vn https://www.reddit.com/r/Piracy/s/Pl2UdgBoJ2

**Comment by Vance-ng-vn** [comment]
> @Vance-ng-vn https://www.reddit.com/r/Piracy/s/Pl2UdgBoJ2

Oh, thank you for this information. It might be an issue with direct-link + pop-up ads from Adsterra.com.  😮‍💨

**Comment by tomtomclub** [comment]
I just use it. In the Android tv box I'm not that worried lol

**Comment by Vance-ng-vn** [comment]
> @Vance-ng-vn https://www.reddit.com/r/Piracy/s/Pl2UdgBoJ2

I’ve researched and removed the 'key active' button, replacing it with a pop-under. This doesn’t change much from the old method, but it completely avoids any misunderstanding from users. You can check it out at https://opensubtitles.stremio.homes

**Comment by Vance-ng-vn** [comment]
> I don't get why this thing has 43 popups. Once we click on install add-on, it takes us to another website that needs to "verify that you're not human" and ask for some random access. I'll never allow that. Meanwhile, the original URL was replaced by yet another ad. So the admins were right on removing this.
> 
> Can't someone just copypaste this to any host without the 490 ads and popups? It's the only plugin I (and my family) needs besides torrentio.

It seems that people difficult to get used to the web push notification ad format. This format allows ads to be displayed even when users are not visiting the website, so I think it’s suitable for addons like Stremio...

Regarding the ad network 'Push.house,' I have checked their ads for a long time, and basically, there are some sexy ads, but they never redirect you to malicious software! However, it seems that this ad network is from Russia, and Google has flagged its links as dangerous!

Maybe I should remove them :((

And as usual, I will direct users to install addons before the pop-under ads appear.

The code will be as simple as this:
![image](https://github.com/user-attachments/assets/62fc2b7e-0e31-473b-899f-b8a7b2a31a91)

**Comment by Vance-ng-vn** [comment]
> Don't remove,If you can earn a little from it it's fine through ads, people shouldn't be so petty the addon works well and is easy to install

The way this type of ad works is by asking you to allow notifications from the website. So, I want to say that 'no one wants to talk about ads,' because from the user's perspective, any type of ad is seen as a scam and harmful! But these are ads that have been authorized to operate, and that's how they work...

I've tried to explain this, but it seems to be impossible!

![image](https://github.com/user-attachments/assets/c3c8ba1a-7cba-4fb2-9a0c-8ac322ec70a7)

**Comment by tomtomclub** [comment]
authorized. The little robot 🤖 
If people want to use the subtitle they will do so, it was fine before ?  People are always complaining, I and many ,are  happy with the subtitle

**Comment by ericvlog** [comment]
@Vance-ng-vn  now it no found on stremio addons please get it back as is most value subtitles addons in stremio !!!

**Comment by tomtomclub** [comment]
> @Vance-ng-vn now it no found on stremio addons please get it back as is most value subtitles addons in stremio !!!

Completely agree with the m8

**Comment by Vance-ng-vn** [comment]
> @Vance-ng-vn now it no found on stremio addons please get it back as is most value subtitles addons in stremio !!!



> > @Vance-ng-vn now it no found on stremio addons please get it back as is most value subtitles addons in stremio !!!
> 
> Completely agree ,m8

I created a new domain and uploaded it to the community list with a new name. This worked instead of negotiating with Stremio and asking them to enable it again :((

The current ads are now reduced to just one 300x250 banner and a hidden ad - after installing the addon and returning to the website, the ad will be displayed.

The source code is just as simple as 2-3 lines like this:
![image](https://github.com/user-attachments/assets/a5a85a12-3b91-4889-81f7-66d56b54d4b1)

**Comment by ericvlog** [comment]
> > @Vance-ng-vn now it no found on stremio addons please get it back as is most value subtitles addons in stremio !!!
> 
> 
> 
> > > @Vance-ng-vn now it no found on stremio addons please get it back as is most value subtitles addons in stremio !!!
> > 
> > Completely agree ,m8
> 
> I created a new domain and uploaded it to the community list with a new name. This worked instead of negotiating with Stremio and asking them to enable it again :((
> 
> The current ads are now reduced to just one 300x250 banner and a hidden ad - after installing the addon and returning to the website, the ad will be displayed.
> 
> The source code is just as simple as 2-3 lines like this:
> ![image](https://github.com/user-attachments/assets/a5a85a12-3b91-4889-81f7-66d56b54d4b1)
> 

Best subtitles add-on !!
Thanks.

**Comment by Vance-ng-vn** [comment]
Last update,

Replaced Direct Link ads with BannerLink on the install button!

![image](https://github.com/user-attachments/assets/b6bc80e8-606a-47ed-8e54-9fa6d5f68df0)- 

If this addon continues to be removed, I might consider shutting it down completely!

- Since removing the DirectLink means that my Banner ads, along with SuperFlix or PornTube, come from the same provider! If it continues to be removed, I will consider this a personal attack!

- If it gets removed, it means I'll have to eliminate ads completely, and the addon won't be able to cover server costs.

** Currently, this addon is running on a VPS with 6 core CPUs, and the monthly ad revenue is only about $10-15.
![image](https://github.com/user-attachments/assets/e4ba1666-3e66-4a83-8bac-2bbe5f9d8522)
![image](https://github.com/user-attachments/assets/2365c372-a34c-4327-bfb2-9d918a0a5bea)

** I have tried to bring the addon back due to many requests for it (I have fulfilled my duty to the users).

** I will always discuss everything openly so that everyone knows exactly what's happening!

**Comment by ericvlog** [comment]
Please do not remove this add-on, it has the most foreign language subtitles then other subtitles add-on.

That is why I stick with stremio, instead of Kodi.

**Comment by tomtomclub** [comment]
What you can do is give the adv more links I use the adv now why not, you can for example supply an extra addon but that link is only available here (With more options)

**Comment by Vance-ng-vn** [comment]
> What you can do is give the adv more links I use the adv now why not, you can for example supply an extra addon but that link is only available here (With more options)

It’s not difficult to block an addon on a platform that you own 🥲

**Comment by tomtomclub** [comment]
It will certainly be difficult, I understand the costs or a server, it's a shame that people cry about it. Popup

**Comment by sleeyax** [comment]
> It will certainly be difficult, I understand the costs or a server, it's a shame that people cry about it. Popup 

No one minds donations. We're talking about malicious (malware) ads here. 99% of Stremio users definitely don't want that.

**Comment by tomtomclub** [comment]
I will make a donation, Please add PayPal for coffee

**Comment by tomtomclub** [comment]
Question is this function working;MovieHash + Auto Adjustment

**Comment by Vance-ng-vn** [comment]
> Question is this function working;MovieHash + Auto Adjustment

1. Movihash: the addon will attempt to search for the movieHash on OpenSubtitles.

2. Auto Adjustment: the addon will try to compare the timestamps with a file that has the same movieHash (either in the same or a different language) and then adjust the timings to match that file!

** However, even though the files may have a movieHash that matches the video’s movieHash, there are only 50-60% of them are accurate.

** OpenSubtitles has no solution for this inaccuracy...

=> Therefore, this feature will not work as expected!

**Comment by tomtomclub** [comment]
It's been banned from the community again.  Its working fine here, keep up the good wrok m8
