### ISSUE TITLE
Trakt Tv

### ISSUE THREAD

**Issue by dexter21767** [danamag/stremio-addons-list#30]
### Addon Manifest URL

https://2ecbbd610840-trakt.baby-beamup.club/manifest.json

### Addon Description

Addon for getting Trakt's public and user lists, recommendations and watch list.

**Comment by danamag** [comment]
This was probably the most requested addon for the longest time.. great job!

**Comment by dexter21767** [comment]
tbh it's an honor seeing that u like it.

**Comment by fahimnwt** [comment]
This is absolutely an great addon, now i hope torrentio will support trakt id too.

**Comment by irljidel00** [comment]
Great add-on and love the extra rpdb support. When I use the website [link](stremio://stremio-addons.netlify.app/catalog.json) it still reports 0.2.2 rather than 0.2.4 is catalog updating?

**Comment by TuupacFR** [comment]
Please include a "Up Next" feature.

**Comment by DryKillLogic** [comment]
It stopped working a few days ago. Is anybody else experiencing the same issue?. Thanks!

**Comment by DryKillLogic** [comment]
@TuupacFR  https://up-next.dontwanttos.top/configure

It would be great if the feature gets integrated into this addon, though.

**Comment by Dude138** [comment]
Can't select any of the options buttons. Just seems to move the panels instead on the configuration page

**Comment by 0zd3m1r** [comment]
it would be nice if an option like "Refresh Lists" is added for lists newly added to the Trakt after authentication. Also all options in the "Generic List" field seem to be enabled when we click configure even if they are disabled. 

Thanks for your effort.

**Comment by SFW-ZA** [comment]
From the river to the sea, Palestine will be free.
huge thanks to Rab1t for histremendous help.

not sure why this has to be included ...

**Comment by conykun** [comment]
That slogan promotes hate. It's totally horrifying and disgusting behavior from the developer.

**Comment by MrSick0ff** [comment]
> Disgusting Rapist apologist logo :vomiting_face: 

Stfu loser, go k some babies.. that would make you feel better

**Comment by MrSick0ff** [comment]
> That slogan promotes hate. It's totally horrifying and disgusting behavior from the developer.

You mom promotes brain damage for raising you

**Comment by FrostyNN** [comment]
Palestinian garbage

**Comment by Germsicle** [comment]
Love it!!! Best categories for sorting of all apps and works flawlessly! Thanks dev!!! Only issue is the drag/drop options on the setup page make it impossible to unchecked anything (popular, watchlist, etc) on a mobile phone. But no biggie just bust out the laptop to configure the addon and its good to go. But if you could give them clickable arrows instead to move things it would be appreciated 🤗

**Comment by Germsicle** [comment]
> Can't select any of the options buttons. Just seems to move the panels instead on the configuration page

It's because they're sliders.... cant change settings on mobile, have to use computer.

**Comment by petermuidev** [comment]
> My Trakt lists stopped working (TraktTV 0.2.7 addon)
> 
> When I re-authenticate my Trakt account in TraktTV 0.2.7 addon, my lists don't appear in the configuration page and the lists are empty in Stremio. Does anyone know how to fix this?

same here!! that suck if have to reconfigure every 3 months with tons of lists

**Comment by lothar-cell** [comment]
yep, it's a pain in the neck, it would be good to be informed about it it in advance in the readme.

**Comment by Germsicle** [comment]
Loved this addon.... until trakt Auth was revoked after 3 months and all my links were deleted 😭 I understand having to re-authenticate, that I could do, but the fact that it deletes all the settings and starts from scratch really sucks and makes this unusable for me. I have switched to the mdblist add to stremio, unfortunately. Will keep an eye out for any updates. Also really hate that you can't unchecked the options when configuring on mobile

**Comment by RokeJulianLockhart** [comment]
> https://github.com/danamag/stremio-addons-list/issues/30#event-15703343368

@danamag, what happened?

**Comment by Fxzzi** [comment]
> what happened? Spam?

it was some... lets say out of pocket... comments about a flag which was present on this addon's logo and banner.

**Comment by lothar-cell** [comment]
A shitty addon for making my list disappear at every re-authentication.
