### ISSUE TITLE
Annatar

### ISSUE THREAD

**Issue by funkypenguin** [danamag/stremio-addons-list#304]
### Addon Manifest URL

https://annatar.elfhosted.com/manifest.json

### Addon Description

This is a free, public [ElfHosted](https://elfhosted.com/) instance of [Annatar](https://gitlab.com/stremio-add-ons/annatar).

[Annatar](https://gitlab.com/stremio-add-ons/annatar) is a self-hosted, fast, just-in-time torrent/debrid search add-on for Stremio providing results in under 3s. Got issues or feature requests? Support your developer on [Ko-fi](https://ko-fi.com/annatar) ❤️, and create issues [here](https://gitlab.com/stremio-add-ons/annatar/-/issues).

[ElfHosted](https://elfhosted.com/) is an [open-source](https://elfhosted.com/open/) PaaS built and run by [geeks](https://geek-cookbook.funkypenguin.co.nz/), which self-hosts [your favorite streaming apps](https://elfhosted.com/guides/media/) for you automatically and easily. Individual, hosted [Annatar+Jackett instances are available](https://store.elfhosted.com/product/annatar-jackett-bundle) (*say, if you need extra indexers*) from $0.15/day, with [$10 free credit](https://elfhosted.com/how-to/spend-elfbuckz/) for [new accounts](https://store.elfhosted.com/my-account/).

## Why use ElfHosted addons?

* [Highly-available](https://status.elfhosted.com/history/public-annatar-stremio-addon), [open-source](https://elfhosted.com/open/) infrastructure / ![](https://img.shields.io/endpoint?url=https%3A%2F%2Fraw.githubusercontent.com%2Fgeek-cookbook%2Felfhosted-upptime%2Fmaster%2Fapi%2Fpublic-annatar-stremio-addon%2Fuptime.json)
* Active contributors to r/StremioAddons subreddit and Discord
* Geek out over [public performance metrics](https://grafana.elfhosted.com/public-dashboards/c78ab8d31f084ef4bccb7017b4518588)

### Language of Content

None

### Choose Labels

- [ ] anime
- [ ] asian drama
- [ ] bollywood
- [ ] cartoons
- [x] debrid support
- [ ] http streams
- [ ] live tv
- [ ] metadata
- [ ] misc
- [X] movies
- [ ] music
- [ ] nsfw
- [ ] podcasts
- [ ] radios
- [ ] subtitles
- [ ] torrents
- [X] tv shows
- [ ] video games

**Comment by enko2974** [comment]
Doesnt work at the moment,2 days

**Comment by RohirrimRider** [comment]
@enko2974 are you still having an issue? There was server maintenance yesterday but everything is up and running.

**Comment by RohirrimRider** [comment]
@danamag can you please add debrid-support label? This is my project and it is debrid focused.

**Comment by javiimp** [comment]
it doesnt work, I cant see any link with this addon in the past days

**Comment by enko2974** [comment]
The same problem,couple of weeks back,is very slow and small number or no links are showing and those links that appear are not playing.

**Comment by javiimp** [comment]
not working since a month ago....any update?

**Comment by g0ldyy** [comment]
I'm taking over annatar development, if you have a problem, please open an issue on the new repository!
https://github.com/g0ldyy/annatar

**Comment by DryKillLogic** [comment]
To reduce the number of questions in the subreddit, please know that this add-on has been deprecated. g0ldyy has moved on to (Comet)[https://stremio-addons.netlify.app/comet-elfhosted].
