### ISSUE TITLE
Jackettio | ElfHosted

### ISSUE THREAD

**Issue by funkypenguin** [danamag/stremio-addons-list#309]
### Addon Manifest URL

https://jackettio.elfhosted.com/manifest.json

### Addon Description

![](https://elfhosted.com/images/logo.png)

This is a public, [ElfHosted](https://elfhosted.com/) instance of [jackettio](https://github.com/arvida42/jackettio) for the Stremio community - Enjoy! (*reasonable [rate-limits](https://github.com/funkypenguin/elf-infra/blob/main/traefik-middleware/middleware-rate-limit-hosted-stremio-addon.yaml) apply*)

[jackettio](https://github.com/arvida42/jackettio) is a self-hostable Stremio Addon which uses Jackett to provide search results - you supply your own indexers / trackers, and it integrates seamlessly with private trackers (*You can also seed back to private trackers if you're a [debrid-link](https://debrid-link.com/) user*)

ElfHosted is an [open-source](https://elfhosted.com/open/) PaaS built and run by [geeks](https://geek-cookbook.funkypenguin.co.nz), which self-hosts your [favorite streaming apps](https://elfhosted.com/guides/media/) for you, automatically and easily. 

Individual, [hosted Jackettio instances are available](https://store.elfhosted.com/product/jackettio/) (*say, if you need to add your private trackers*) from $0.05/day, with [$10 free credit](https://elfhosted.com/how-to/spend-elfbuckz/) for [new accounts](https://store.elfhosted.com/my-account/).

#### Why use [ElfHosted Stremio addons](https://elfhosted.com/stremio-addons/)?

* ✅ [Highly-available](https://status.elfhosted.com/history/public-jackettio-stremio-addon), [open-source](https://elfhosted.com/open/) infrastructure / ![](https://img.shields.io/endpoint?url=https%3A%2F%2Fraw.githubusercontent.com%2Fgeek-cookbook%2Felfhosted-upptime%2Fmaster%2Fapi%2Fpublic-jackettio-stremio-addon%2Fuptime.json)
* ✅ Active contributors to r/StremioAddons subreddit and Discord
* ✅ Geek out over [public performance metrics](https://fnky.nz/grafana-jackettio)

### Language of Content

English (en-US)

### Choose Labels

- [ ] anime
- [ ] asian drama
- [ ] bollywood
- [ ] cartoons
- [X] debrid support
- [ ] http streams
- [ ] live tv
- [ ] metadata
- [ ] misc
- [X] movies
- [ ] music
- [ ] nsfw
- [ ] podcasts
- [ ] radios
- [ ] subtitles
- [ ] torrents
- [X] tv shows
- [ ] video games

**Comment by arvida42** [comment]
The manifest issue was fixed
