### ISSUE TITLE
StremiO-D 2

### ISSUE THREAD

**Issue by mikmc55** [danamag/stremio-addons-list#326]
### Addon Manifest URL

https://stremi-od2.vercel.app/manifest.json

### Addon Description

Movie & TV Streams from Open Directories

### Language of Content

None

### Choose Labels

- [X] anime
- [ ] asian drama
- [ ] bollywood
- [ ] cartoons
- [ ] debrid support
- [ ] http streams
- [ ] live tv
- [ ] metadata
- [ ] misc
- [X] movies
- [ ] music
- [ ] nsfw
- [ ] podcasts
- [ ] radios
- [ ] subtitles
- [ ] torrents
- [X] tv shows
- [ ] video games

**Comment by tsaridas** [comment]
maybe do  HEAD request to validate links  & cache ? guess that would overload but at least have valid results.

**Comment by mikmc55** [comment]
i do make validation requests before the json is parsed from a get request , the problem is with open directory files they can be set not to stream in various ways but still return 200. i  come back to this addon when i can think how to improve it but as of yet, that issue remains so its either publish it as is or not at all atm..if you have anything you would like to suggest by all means we can try it
its not particularly sensitive code , just too many google ninjas now but i added you to it if you want a look

**Comment by mikmc55** [comment]
Updated to v 2.02 w / fixes
