### ISSUE TITLE
ℋ  🌎 LATINO TV EN DIRECTO GRATIS 🌎  Ỵ

### ISSUE THREAD

**Issue by mik25** [danamag/stremio-addons-list#34]

**Comment by rodimus75** [comment]
Can anyone fix this add-on please. Stop the bullshit ADS named Malo TV and everyone on the add-on ... this is one of the best add-ons but literally have been ruined with that kind of ADS!

**Comment by rodimus75** [comment]
Can someone fix this plugin please? Enough with the bullshit ads called Malo TV and all the plug-in banner ads... literally ruined with those kind of bullshit ads!
Get rid of those fucking ads that constantly appears in any program/movie/series, etc!

**Comment by mik25** [comment]
Viendo como lo pediste tan amablemente



¡No!

**Comment by rodimus75** [comment]
> Viendo como lo pediste tan amablemente
> 
> ¡No!

Is the best you can do? Then don't do anything and don't be so weeping if you don't want to cooperate!
If having crap advertising is fine for you and you can handle it, it's not for other people and even more so when it's crap advertising!
