### ISSUE TITLE
ℋ ✨ MAX TV ✨ 󠁴󠁭󠁢󠁿 Ỵ

### ISSUE THREAD

**Issue by mik25** [danamag/stremio-addons-list#37]
### Addon Manifest URL

https://maxtv.surge.sh/manifest.json
### Addon Description

Mixed World IPTV Streams

**Comment by challou77** [comment]
Today It doesn't work ????!!!!!

**Comment by freestreamEU** [comment]
thank's for the work guys 8 Since few days Tv stream from Belgium and France are not working any more! does someone 've a solution?

**Comment by owen-the-kid** [comment]
it doesnt work anymore
