### ISSUE TITLE
Torrentio OC

### ISSUE THREAD

**Issue by Ghawas1981** [danamag/stremio-addons-list#382]
### Addon Manifest URL

https://torrentio.strem.fun/providers=yts,eztv,rarbg,1337x,thepiratebay,kickasstorrents,torrentgalaxy,magnetdl,horriblesubs,nyaasi,tokyotosho,anidex|qualityfilter=scr,cam|limit=1|debridoptions=torrentlinks|offcloud=VHK7OoGO57kH1JOO9VlNo8AdRVF0qLD8/manifest.json

### Language of Content

English (en-US)

### Choose Labels

- [x] anime
- [x] asian drama
- [x] bollywood
- [x] cartoons
- [x] debrid support
- [x] http streams
- [x] live tv
- [x] metadata
- [x] misc
- [x] movies
- [x] music
- [x] nsfw
- [x] podcasts
- [x] radios
- [x] subtitles
- [x] torrents
- [x] tv shows
- [x] video games

**Comment by megadrive** [comment]
@danamag should this be here? it's a preconfigured addon by someone other than the original author with a private apikey in the config.

**Comment by sleeyax** [comment]
Hi @Ghawas1981, your **private API key** is exposed in the addon URL. Please **change it ASAP** as others may now have access to it as well. 

Please don't submit any preconfigured addons here in the first place, that's not what this list is intended for. You are supposed to submit unique addons and torrentio is already in the list (published by the original developer). 

If you have any question let me know. I'm closing this issue so the addon gets removed from this list.
