### ISSUE TITLE
Peerflix v2

### ISSUE THREAD

**Issue by kekazoh** [danamag/stremio-addons-list#384]
### Addon Manifest URL

https://peerflix.mov/manifest.json

### Addon Description

Peerflix addon for stremio. Including Spanish (from Spain) and English torrents for movies and tv shows.
From sources like Bitsearch.to, Popcorntime, Dontorrent, Mejortorrent and Wolfmax4K.

Addon de peerflix para Stremio. Incluye torrents en español (de españa) y en ingles para películas y series.
Torrents extraidos de fuentes como Bitsearch.to, Popcorntime, Dontorrent, Mejortorrent and Wolfmax4k.

### Language of Content

Spanish; Castilian (es-ES)

### Choose Labels

- [ ] anime
- [ ] asian drama
- [ ] bollywood
- [ ] cartoons
- [ ] debrid support
- [ ] http streams
- [ ] live tv
- [ ] metadata
- [ ] misc
- [X] movies
- [ ] music
- [ ] nsfw
- [ ] podcasts
- [ ] radios
- [ ] subtitles
- [X] torrents
- [X] tv shows
- [ ] video games

**Comment by duda1972** [comment]
Muchísimas gracias por el tiempo que le dedicas... 🤗
