### ISSUE TITLE
Stremify (Elfhosted)

### ISSUE THREAD

**Issue by infvortx** [danamag/stremio-addons-list#395]
### Addon Manifest URL

https://stremify.elfhosted.com

### Addon Description

A multi-server, multi-lang HTTP streaming addon.

### Language of Content

Multilingual (Default)

### Choose Labels

- [X] anime
- [X] asian drama
- [ ] bollywood
- [ ] cartoons
- [ ] debrid support
- [X] http streams
- [ ] live tv
- [X] metadata
- [ ] misc
- [X] movies
- [ ] music
- [ ] nsfw
- [ ] podcasts
- [ ] radios
- [ ] subtitles
- [ ] torrents
- [X] tv shows
- [ ] video games

**Comment by Manchmal1** [comment]
Was habe ich falsch gemacht 
Können Sie mir bitte erklären 
Wie ich das ändern kann bitte

**Comment by Manchmal1** [comment]
> ### Addon Manifest URL
> 
> https://stremify.elfhosted.com/manifest.json
> ### Addon Beschreibung
> 
> Ein Multi-Server, Multi-lang HTTP Streaming Addon.
> ### Sprache des Inhalts
> 
> Mehrsprachig (Standard)
> ### Wähle Etiketten
> 
>     * [x] anime
> 
>     * [x] asian Drama
> 
>     * [ ] Bollywood
> 
>     * [ ] Cartoon
> 
>     * [ ] Debrid-Unterstützung
> 
>     * [x] http-Streams
> 
>     * [ ] Live TV
> 
>     * [x] Metadaten
> 
>     * [ ] misc
> 
>     * [x] Filme
> 
>     * [ ] Musik
> 
>     * [ ] nsfw
> 
>     * [ ] Podcasts
> 
>     * [ ] Radio
> 
>     * [ ] Untertitel
> 
>     * [ ] torrents
> 
>     * [x] TV-Shows
> 
>     * [ ] Videospiele



> War tote hasse ich Können Sie mir zerre Wie mir das ändern kann

Gerne würde mich freuen

**Comment by Manchmal1** [comment]
Was muss ich jetzt tun 
Versuche es zu ändern geht nicht 
Woe mache ich das bitte
