### ISSUE TITLE
Mamma Mia

### ISSUE THREAD

**Issue by UrloMythus** [danamag/stremio-addons-list#405]
### Addon Manifest URL

https://mammamia-urlo-mammamia.hf.space/manifest.json

### Addon Description

This is an Add-on providing HTTPS Streams for Italian Movies, 3D Movies, Series, Anime and some Live TV channels.

### Language of Content

Italian (it-IT)

### Choose Labels

- [X] anime
- [ ] asian drama
- [ ] bollywood
- [ ] cartoons
- [ ] debrid support
- [X] http streams
- [X] live tv
- [ ] metadata
- [ ] misc
- [X] movies
- [ ] music
- [ ] nsfw
- [ ] podcasts
- [ ] radios
- [ ] subtitles
- [ ] torrents
- [X] tv shows
- [ ] video games

**Comment by Yoshinizar** [comment]
Salve potete aggiungere anche altri siti come eurostreaming, e uno anche per gli anime come animeworld o animesaturn? Grazie

**Comment by UrloMythus** [comment]
> Salve potete aggiungere anche altri siti come eurostreaming, e uno anche per gli anime come animeworld o animesaturn? Grazie

Ciao, se intendi eurostreaming.casino (la copia di guardaserie) allora è già aggiunto dall'add-on Stremify. Se invece intendi eurostreaming.money si potrebbe fare anche se non ha molte informazioni per identificare le serie, quali IMDB o data. Per quanto riguarda gli anime per ora c'è filmpertutti come provider.

**Comment by Yoshinizar** [comment]
Si intendevo eurostreaming.food, per gli anime filmpertutti è come se non esistesse non ha nulla, se magari più avanti, potete implementare animeworld o animesaturn, sarebbe decisamente meglio, grazie mille per la creazione dell'addon 👍🏻

**Comment by UrloMythus** [comment]
> @UrloMythus Si intendevo eurostreaming.food, per gli anime filmpertutti è come se non esistesse non ha nulla, se magari più avanti, potete implementare animeworld o animesaturn, sarebbe decisamente meglio, grazie mille per la creazione dell'addon 👍🏻

Si in futuro si potrebbe fare, temo però non in tempi brevi.

**Comment by Asimov1962** [comment]
Perché non entri nel gruppo Stremio Italia su Telegram?  Confrontarti e sapere cosa vogliono gli utenti che usano Stremio ti agevolerebbe il lavoro. Al momento posso darti un feedback positivo, solo che spesso soprattutto con i files con qualità 1080 si blocca tutto e bisogna riavviare Stremio. Con il tuo siamo già a 3 addon dedicati a film e serie italiani, non si potrebbe unire le fonti e farne uno solo? Altra domanda: Stremio dovrebbe puntare sulla qualità, così lo fate diventare un clone di Veezie, perché non creare un addon che riunisca fonti di Torrentio solo in italiano? Spero di vederti sul gruppo Telegram       https://t.me/Stremio_Italia

**Comment by UrloMythus** [comment]
> Perché non vieni nel gruppo Stremio Italia su Telegram? Confrontarti e sapere cosa vogliono gli utenti che usano Stremio ti agevolerebbe il lavoro. Al momento posso darti un feedback positivo, solo che spesso soprattutto con i files con qualità 1080 si blocca tutto e bisogna riavviare Stremio inoltre le TV al momento non ne funziona nessuna. Con il tuo siamo già a 3 addon dedicati a film e serie italiani, non si potrebbe unire le fonti e farne uno solo? Altra domanda: Stremio dovrebbe puntare sulla qualità, così lo fate diventare un clone di Veezie, perché non creare un addon che riunisca fonti di Torrentio solo in italiano? Spero di vederti sul gruppo Telegram https://t.me/Stremio_Italia

Il motivo è che non sapevo esistesse

**Comment by Asimov1962** [comment]
Ho visto che hai accettato e sei entrato nel gruppo e ti ringrazio per questo, nel gruppo ci sono vari admin dei maggiori gruppi di streaming, oltre a qualche moderatore di Veezie, ti consiglierei di evitare discussioni sul gruppo ma al limite contattarli in privato, uno di questi è Steve che ti ha appena posto una domanda sul gruppo, chiaramente tutto senza impegno, non vogliamo stressarti

**Comment by UrloMythus** [comment]
> Salve potete aggiungere anche altri siti come eurostreaming, e uno anche per gli anime come animeworld o animesaturn? Grazie

Aggiunto animeworld
