### ISSUE TITLE
Film ve dizi

### ISSUE THREAD

**Issue by yusiqo** [danamag/stremio-addons-list#410]
### Addon Manifest URL

https://eklenti.yusiqo.com/manifest.json

### Addon Description

Fullhd film izlesene ve Diziyou sitesinden.

### Language of Content

Turkish (tr-TR)

### Choose Labels

- [ ] anime
- [ ] asian drama
- [ ] bollywood
- [ ] cartoons
- [ ] debrid support
- [X] http streams
- [ ] live tv
- [ ] metadata
- [ ] misc
- [ ] movies
- [ ] music
- [ ] nsfw
- [ ] podcasts
- [ ] radios
- [ ] subtitles
- [ ] torrents
- [ ] tv shows
- [ ] video games

**Comment by ItsSparks** [comment]
how does this work? i can't seem to find any new movies or series like its very limited is there something i'm doing wrong?

**Comment by yusiqo** [comment]
> how does this work? i can't seem to find any new movies or series like its very limited is there something i'm doing wrong?

The add-on is prepared only for Turkish dubbed movies and for Turks. I purposely made the catalog limited so that the server would not receive too many requests. If you search, you can find what you want.
