### ISSUE TITLE
IPTVorg

### ISSUE THREAD

**Issue by mikmc55** [danamag/stremio-addons-list#419]
### Addon Manifest URL

https://stremio-iptv-org.vercel.app/manifest.json

### Addon Description

Iptv.org Stremio Addon
8000+ Fully Searchable Streams in Countries and Categories

### Language of Content

None

### Choose Labels

- [ ] anime
- [ ] asian drama
- [ ] bollywood
- [ ] cartoons
- [ ] debrid support
- [ ] http streams
- [X] live tv
- [ ] metadata
- [ ] misc
- [ ] movies
- [ ] music
- [ ] nsfw
- [ ] podcasts
- [ ] radios
- [ ] subtitles
- [ ] torrents
- [ ] tv shows
- [ ] video games

**Comment by Germsicle** [comment]
Awesome! Would be great if we could choose which channel categories to install instead of all of them. But atleast there is a sorting option! 👍

**Comment by mikmc55** [comment]
Redeployed
