### ISSUE TITLE
hooligan

### ISSUE THREAD

**Issue by bytedeal3r** [danamag/stremio-addons-list#433]
### Addon Manifest URL

https://docker-hooligan.onrender.com/manifest.json

### Addon Description

Live Sport Events! Watch Formula1, Soccer, MLB, NFL, MotoGP, NBA and many more live sport events directly in stremio

### Language of Content

English (en-US)

### Choose Labels

- [ ] anime
- [ ] asian drama
- [ ] bollywood
- [ ] cartoons
- [ ] debrid support
- [X] http streams
- [X] live tv
- [ ] metadata
- [ ] misc
- [ ] movies
- [ ] music
- [ ] nsfw
- [ ] podcasts
- [ ] radios
- [ ] subtitles
- [ ] torrents
- [ ] tv shows
- [ ] video games

**Comment by joepnxsun** [comment]
Does the link only show for a live game/race?

**Comment by joepnxsun** [comment]
Does the stream only show for a live game/race or this doesn't have any stream links at the moment?

**Comment by bytedeal3r** [comment]
it will only show links when something is live or is about to start (1 hour ish before, depends on source)

**Comment by Germsicle** [comment]
Can confirm it works!! Watching an event right now. Links show up but might not load until beginning of event. Thanks dev!!!!

**Comment by cdkao** [comment]
NFL live streams seem to work fine.  However, other sports do not work.

**Comment by Bigfella707** [comment]
I'm can't seem to get any of live tv links to work I'm using Stremio add on fire tv

**Comment by Bigfella707** [comment]
> NFL live streams seem to work fine.  However, other sports do not work. 

What are you running im using Stremio apk on fire tv and none of the links play
