### ISSUE TITLE
TMDB Dice

### ISSUE THREAD

**Issue by Vance-ng-vn** [danamag/stremio-addons-list#437]
### Addon Manifest URL

https://43433fff4541-tmdb-dice.baby-beamup.club/manifest.json

### Language of Content

None

### Choose Labels

- [ ] anime
- [ ] asian drama
- [ ] bollywood
- [ ] cartoons
- [ ] debrid support
- [ ] http streams
- [ ] live tv
- [X] metadata
- [ ] misc
- [X] movies
- [ ] music
- [ ] nsfw
- [ ] podcasts
- [ ] radios
- [ ] subtitles
- [ ] torrents
- [ ] tv shows
- [ ] video games

**Comment by Rufusnightly** [comment]
![IMG_20241016_065659](https://github.com/user-attachments/assets/c59ba0fd-e8a8-47a9-a1d3-f6eb3e315482)
Not work another time 
![Screenshot_2024-10-16-06-55-34-26_5a1e11fa41055108da81eb54eea93a2a](https://github.com/user-attachments/assets/e44e2327-a6d7-40ee-95b8-0015b776da7f)

**Comment by Vance-ng-vn** [comment]
> ![IMG_20241016_065659](https://private-user-images.githubusercontent.com/148594216/376894805-c59ba0fd-e8a8-47a9-a1d3-f6eb3e315482.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkxMjgxMTcsIm5iZiI6MTcyOTEyNzgxNywicGF0aCI6Ii8xNDg1OTQyMTYvMzc2ODk0ODA1LWM1OWJhMGZkLWU4YTgtNDdhOS1hMWQzLWY2ZWIzZTMxNTQ4Mi5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxN1QwMTE2NTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04NjIxYzNkNTRhYmVjZjdkMDc4OTNjYWY5NjZjMGI3MTMwMmFhZjJmYmZiOWFmYmI5NWIxNTg1MzliN2ZmZjkxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.slZbhZImGJ1QxvrhP81xqKKLcWqw0e5qwGOtzOeaslc) Not work another time ![Screenshot_2024-10-16-06-55-34-26_5a1e11fa41055108da81eb54eea93a2a](https://private-user-images.githubusercontent.com/148594216/376894611-e44e2327-a6d7-40ee-95b8-0015b776da7f.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkxMjgxMTcsIm5iZiI6MTcyOTEyNzgxNywicGF0aCI6Ii8xNDg1OTQyMTYvMzc2ODk0NjExLWU0NGUyMzI3LWE2ZDctNDBlZS05NWI4LTAwMTViNzc2ZGE3Zi5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxN1QwMTE2NTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yMjMyOWI0YjcxMjU1ODdmNGIwNTk0ZTNiNzNkZjczNTViOTNjYjQyZDE5OTNlODYzZmI2Y2JmMzU3NzhkYTQzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.duuDmI0zYVn5RVWrymfusM_HhhAw1-7dbpd-4jYKu2Y)

"This is a malicious addon, so it has been removed from Stremio! 😄😄😄"

I have a backup version here:  https://tmdb-dice.stremio.homes
