### ISSUE TITLE
[ Hanime.TV ] 

### ISSUE THREAD

**Issue by danamag** [danamag/stremio-addons-list#49]
### Addon Manifest URL

https://a0da031547f5-hanime-stremio-main.baby-beamup.club/manifest.json

### Addon Description

(working anime-src version) Enjoy your unlimited hentai & anime collection. https://github.com/anime-src/hanime-stremio

### Choose Labels

- [X] anime
- [ ] debrid support
- [X] http streams
- [ ] live tv
- [ ] metadata
- [ ] misc
- [ ] movies
- [ ] music
- [X] nsfw
- [ ] radios
- [ ] subtitles
- [ ] torrents
- [ ] tv shows
- [ ] video games

**Comment by danamag** [comment]
There are two Hanime addons at the time of writing (26 oct 2022), both seem to work

**Comment by thekingoftown** [comment]
No streams can be found on the GoogleTV Chromecast version but works fine on android and desktop

**Comment by az95zzam** [comment]
> ### Addon Manifest URL
> https://a0da031547f5-hanime-stremio-main.baby-beamup.club/manifest.json
> 
> ### Addon Description
> (working anime-src version) Enjoy your unlimited hentai & anime collection. https://github.com/anime-src/hanime-stremio
> 
> ### Language of Content
> _No response_
> 
> ### Choose Labels
> * [x]  anime
> * [ ]  debrid support
> * [x]  http streams
> * [ ]  live tv
> * [ ]  metadata
> * [ ]  misc
> * [ ]  movies
> * [ ]  music
> * [x]  nsfw
> * [ ]  radios
> * [ ]  subtitles
> * [ ]  torrents
> * [ ]  tv shows
> * [ ]  video games
