### ISSUE TITLE
Mico-Leão Dublado 🇧🇷

### ISSUE THREAD

**Issue by danamag** [danamag/stremio-addons-list#50]
### Addon Manifest URL

https://27a5b2bfe3c0-stremio-brazilian-addon.baby-beamup.club/manifest.json

### Addon Description

Assista a FILMES dublados em português de GRAÇA! HD e FULLHD!

### Language of Content

Brazilian Portuguese (pt-BR)

### Choose Labels

- [ ] anime
- [ ] debrid support
- [ ] http streams
- [ ] live tv
- [ ] metadata
- [ ] misc
- [X] movies
- [ ] music
- [ ] nsfw
- [ ] radios
- [ ] subtitles
- [X] torrents
- [ ] tv shows
- [ ] video games

**Comment by murissi** [comment]
Esse é bão

**Comment by RafaelDilva** [comment]
Tá com problema?

**Comment by hik-sudo** [comment]
porque não funciona mais?

**Comment by hik-sudo** [comment]
não tem mais o addon no stremio

**Comment by laurorual** [comment]
não funciona/atualiza a um bom tempo, o negocio agora é usar o Brazuca Torrents

**Comment by nowadays666** [comment]
Morreu ??

**Comment by luizeba** [comment]
Não funciona mais. Estou usando o Brazuca Torrents.

**Comment by jikk0313** [comment]
qual addon desse?
