### ISSUE TITLE
isratv for streamio

### ISSUE THREAD

**Issue by danamag** [danamag/stremio-addons-list#54]
### Addon Manifest URL

https://stremioaddon.vercel.app/manifest.json

### Addon Description

watch israel tv

### Language of Content

Hebrew (he-IL)

### Choose Labels

- [ ] anime
- [ ] debrid support
- [ ] http streams
- [X] live tv
- [ ] metadata
- [ ] misc
- [ ] movies
- [ ] music
- [ ] nsfw
- [ ] radios
- [ ] subtitles
- [ ] torrents
- [ ] tv shows
- [ ] video games

**Comment by Ejw3ly** [comment]
1

**Comment by Ejw3ly** [comment]
1

**Comment by naorfarag** [comment]
Can you fix channel14/CH14 that not working? thanks!

**Comment by mo7ub** [comment]
trash

**Comment by MrSick0ff** [comment]
Free Palestine

**Comment by MorYakobov** [comment]
The link is not wroking
![image](https://github.com/danamag/stremio-addons-list/assets/164322050/eaf4f67c-bf9e-4e27-9792-8cfdfeabd203)
<img width="645" alt="Screenshot 2024-03-22 at 18 01 03" src="https://github.com/danamag/stremio-addons-list/assets/164322050/f2738d13-2d87-45bf-b5fe-363346fac7cc">

**Comment by eifr** [comment]
![image](https://github.com/user-attachments/assets/5da8f0ea-e1e0-4729-918e-d8e7285a740e)
seems to be working
