### ISSUE TITLE
Media Fusion

### ISSUE THREAD

**Issue by danamag** [danamag/stremio-addons-list#55]
### Addon Manifest URL

https://882b9915d0fe-stremio-tamilblasters.baby-beamup.club/manifest.json

### Addon Description

TamilBlasters add-on for watch tamil, hindi, malayalam, kannada, english, dubbed movies & series . Created By: Mohamed Zumair. Source: https://github.com/mhdzumair/tamilblasters_streamio_addon

### Language of Content

Indian (General)

### Choose Labels

- [ ] anime
- [ ] debrid support
- [ ] http streams
- [ ] live tv
- [ ] metadata
- [ ] misc
- [X] movies
- [ ] music
- [ ] nsfw
- [ ] radios
- [ ] subtitles
- [X] torrents
- [X] tv shows
- [ ] video games

**Comment by porusbaker** [comment]
Hi,

Thank you for the awesome add-on. Will it be possible to choose the categories. For example I do not understand Tamil, Kannada etc. but love to see the dubbed version of the movie. Hence if possible please add an option to choose which catalog to display.

**Comment by mhdzumair** [comment]
@porusbaker Thanks for your suggestion. I have added the category select option, see here. https://github.com/mhdzumair/tamilblasters_stremio_addon/issues/15

**Comment by mhdzumair** [comment]
@danamag please set following labels 


### Choose Labels

* [ ]  anime
* [x]  debrid support
* [x]  http streams
* [ ]  live tv
* [x]  metadata
* [ ]  misc
* [x]  movies
* [ ]  music
* [ ]  nsfw
* [ ]  radios
* [ ]  subtitles
* [x]  torrents
* [x]  tv shows
* [ ]  video games

**Comment by Nachiketin** [comment]
@mhdzumair could it be possible to add Marathi language please?

**Comment by mhdzumair** [comment]
@Nachiketin please create an issue [here](https://github.com/mhdzumair/MediaFusion/issues) with a site that provide Marathi language movies.
