### ISSUE TITLE
JavJT

### ISSUE THREAD

**Issue by danamag** [danamag/stremio-addons-list#58]
### Addon Manifest URL

https://c73485b8a7a2-javjt.baby-beamup.club/manifest.json

### Language of Content

Japanese (ja-JP)

### Choose Labels

- [ ] anime
- [ ] debrid support
- [ ] http streams
- [ ] live tv
- [ ] metadata
- [ ] misc
- [ ] movies
- [ ] music
- [X] nsfw
- [ ] radios
- [ ] subtitles
- [x] torrents
- [ ] tv shows
- [ ] video games

**Comment by thekingoftown** [comment]
No streams can be found on the GoogleTV Chromecast version but works fine on android and desktop
