### ISSUE TITLE
Add/Replace Hanime link with this

### ISSUE THREAD

**Issue by AlecMcCutcheon** [danamag/stremio-addons-list#6]
I realized that the Hanime.TV addon was barely working with the links provided, the catalog would load but 90% of the library had no links. So I found a more up to date project for the addon and deployed it to beamup for all to use. also tweaked it slightly. lmk if there is any issues with it but from what I can tell, it works great.

https://a0da031547f5-hanime-stremio-main.baby-beamup.club/manifest.json

**Comment by danamag** [comment]
@AlecMcCutcheon i checked it and the link you provided seems to work, i will change it

**Comment by danamag** [comment]
@AlecMcCutcheon done, thanks for the correction!
