### ISSUE TITLE
KOLKOL by dexter21767

### ISSUE THREAD

**Issue by dexter21767** [danamag/stremio-addons-list#62]
### Addon Manifest URL

https://2ecbbd610840-kolkol.baby-beamup.club/manifest.json

### Addon Description

stream everything over https with multiple subtitles

### Language of Content

Multilingual (Default)

### Choose Labels

- [X] anime
- [X] asian drama
- [X] bollywood
- [X] cartoons
- [ ] debrid support
- [X] http streams
- [ ] live tv
- [X] metadata
- [X] movies
- [ ] misc
- [ ] music
- [ ] nsfw
- [ ] podcasts
- [ ] radios
- [ ] subtitles
- [ ] torrents
- [X] tv shows
- [ ] video games

**Comment by retiarylime** [comment]
Why is it not working? It keeps loading all the time.

**Comment by Ramghh** [comment]
This addon doesn't really work.
