### ISSUE TITLE
Addon Name

### ISSUE THREAD

**Issue by 813076** [danamag/stremio-addons-list#66]
### Addon Manifest URL

Torrento

### Language of Content

English (en-US)

### Choose Labels

- [X] anime
- [X] asian drama
- [X] bollywood
- [X] cartoons
- [X] debrid support
- [X] http streams
- [X] live tv
- [ ] metadata
- [ ] misc
- [X] movies
- [X] music
- [ ] nsfw
- [X] podcasts
- [ ] radios
- [X] subtitles
- [X] torrents
- [X] tv shows
- [ ] video games

**Comment by danamag** [comment]
i don't know what this is, but it's not a new addon, closing it
