### ISSUE TITLE
HLTV Confirmed

### ISSUE THREAD

**Issue by mrcanelas** [danamag/stremio-addons-list#67]
### Addon Manifest URL

https://94c8cb9f702d-hltv-confirmed-addon.baby-beamup.club/manifest.json

### Addon Description

Watch the biggest Counter Strike: Global Offensive championships in real time.

### Language of Content

Multilingual (Default)

### Choose Labels

- [ ] anime
- [ ] asian drama
- [ ] bollywood
- [ ] cartoons
- [ ] debrid support
- [ ] http streams
- [X] live tv
- [ ] metadata
- [ ] misc
- [ ] movies
- [ ] music
- [ ] nsfw
- [ ] podcasts
- [ ] radios
- [ ] subtitles
- [ ] torrents
- [ ] tv shows
- [ ] video games

**Comment by rodimus75** [comment]
Add-on does not work, please fix.
