### ISSUE TITLE
Addon Name

### ISSUE THREAD

**Issue by medoyamy** [danamag/stremio-addons-list#68]
### Addon Manifest URL

https://tv.egydead.live/a3/

### Addon Description

mm

### Language of Content

Arabic (ar-SA)

### Choose Labels

- [X] anime
- [ ] asian drama
- [ ] bollywood
- [ ] cartoons
- [ ] debrid support
- [ ] http streams
- [ ] live tv
- [ ] metadata
- [ ] misc
- [X] movies
- [X] music
- [ ] nsfw
- [ ] podcasts
- [ ] radios
- [X] subtitles
- [ ] torrents
- [X] tv shows
- [ ] video games

**Comment by danamag** [comment]
i don't know what this is, but it's not a new addon, closing it
