### ISSUE TITLE
[18+][Live] Chaturbate

### ISSUE THREAD

**Issue by sleeyaxx** [danamag/stremio-addons-list#692]
### Addon Manifest URL

https://43433fff4541-130924.baby-beamup.club/chaturbate/manifest.json

### Language of Content

None

### Choose Labels

- [X] anime
- [X] asian drama
- [X] bollywood
- [X] cartoons
- [X] debrid support
- [X] http streams
- [X] live tv
- [X] metadata
- [X] misc
- [X] movies
- [X] music
- [X] nsfw
- [X] podcasts
- [X] radios
- [X] subtitles
- [X] torrents
- [X] tv shows
- [X] video games

**Comment by Germsicle** [comment]
Dude can you stop spamming github with these constant openings and closings of these apps?!

**Comment by sleeyaxx** [comment]
> Dude can you stop spamming github with these constant openings and closings of these apps?!

Actually, he closed it, and I will reopen it!

**Comment by sleeyax** [comment]
> Dude can you stop spamming github with these constant openings and closings of these apps?!

We're currently getting spammed by this no-life bully spammer. Don't worry we'll have a permanent solution to this soon.
