### ISSUE TITLE
TugaAddon

### ISSUE THREAD

**Issue by Afonso24770** [danamag/stremio-addons-list#704]
### Addon Manifest URL

https://tugaplay.onrender.com/manifest.json

### Addon Description

Tuga addon

### Language of Content

Portuguese (pt-PT)

### Choose Labels

- [ ] anime
- [ ] asian drama
- [ ] bollywood
- [X] cartoons
- [ ] debrid support
- [ ] http streams
- [ ] live tv
- [ ] metadata
- [ ] misc
- [X] movies
- [ ] music
- [ ] nsfw
- [ ] podcasts
- [ ] radios
- [ ] subtitles
- [ ] torrents
- [ ] tv shows
- [ ] video games

**Comment by sleeyax** [comment]
@Afonso24770 your addon mangiest is unreachable (404 not found).
