### ISSUE TITLE
AUS TV

### ISSUE THREAD

**Issue by joebckFeg8** [danamag/stremio-addons-list#711]
### Addon Manifest URL

https://raw.githubusercontent.com/joebckFeg8/austv/refs/heads/main/manifest.json

### Addon Description

AUS TV provides access to Australian free-to-air channels.

### Language of Content

English (en-US)

### Choose Labels

- [ ] anime
- [ ] asian drama
- [ ] bollywood
- [ ] cartoons
- [ ] debrid support
- [ ] http streams
- [X] live tv
- [ ] metadata
- [ ] misc
- [ ] movies
- [ ] music
- [ ] nsfw
- [ ] podcasts
- [ ] radios
- [ ] subtitles
- [ ] torrents
- [ ] tv shows
- [ ] video games

**Comment by joebckFeg8** [comment]
@sleeyax @danamag updated the link because the last host deleted the files

**Comment by joebckFeg8** [comment]
https://raw.githubusercontent.com/joebckFeg8/austv/refs/heads/main/manifest.json

**Comment by sleeyax** [comment]
@joebckFeg8 you can't use GitHub to host your manifest. Addons must be deployed to a webserver. You can use beamup for that if you're looking for a free option (google "stremio beamup").
