### ISSUE TITLE
Worldwide Sports TV

### ISSUE THREAD

**Issue by DryKillLogic** [danamag/stremio-addons-list#713]
### Addon Manifest URL

https://worldwide-sports-tv.vercel.app/manifest.json

### Addon Description

Worldwide Sports TV provides access to a diverse range of sports events and channels from around the globe.

### Language of Content

Multilingual (Default)

### Choose Labels

- [ ] anime
- [ ] asian drama
- [ ] bollywood
- [ ] cartoons
- [ ] debrid support
- [ ] http streams
- [X] live tv
- [X] metadata
- [ ] misc
- [ ] movies
- [ ] music
- [ ] nsfw
- [ ] podcasts
- [ ] radios
- [ ] subtitles
- [ ] torrents
- [ ] tv shows
- [ ] video games

**Comment by DryKillLogic** [comment]
---placeholder---

**Comment by Manchmal1** [comment]
Danke

**Comment by Blorp-blorp** [comment]
Thank you for building this. I just installed the adding but no content shows up in Stremio. Is that expected behaviour at this point? I get this is in beta right now.

**Comment by Manchmal1** [comment]
Ich bekomme es auch nicht hin ,habe es installiert es kommen keine Inhalte.
Wissen Sie wie ich das ändern kann bitte

Blorp-blorp ***@***.***> schrieb am Di., 29. Okt. 2024, 22:20:

**Comment by DryKillLogic** [comment]
> Thank you for building this. I just installed the adding but no content shows up in Stremio. Is that expected behaviour at this point? I get this is in beta right now.

You access it either from the discover section or search.

**Comment by ZeGentlemen** [comment]
I can't thank you enough for this addon. I know that this is still underdevelopment but the 24/7 streams don't seem to be working even with vlc as the external player

**Comment by Manchmal1** [comment]
Ja,ich bekomme auch keine Inhalte 
Können Sie mir erklären wie ich das machen muss um Inhalte zu sehen senderliste filme serien

**Comment by Lukefleming1995** [comment]
Thank you! Really looking forward to it after the death of hooligan. 

Cheers!

**Comment by Lukefleming1995** [comment]
Looking forward to it!

**Comment by Ballbag100** [comment]
Does not seem to be working on regular android, or windows. Using several external players. Stream never loads and then boots me out. Any ideas? Thanks!! Looking forward to this.

**Comment by DryKillLogic** [comment]
People don't seem to understand that this is a soft launch/beta for a reason, and instead of helping, they just downvote it. I'm taking it down; good luck finding it.

**Comment by Ballbag100** [comment]
Whoa brother! I wasn't trying to be critical, was just thinking maybe I was doing something wrong /my input could be helping development is all. Wish you wouldn't take it down, I know at least I am super grateful.

**Comment by Ballbag100** [comment]
Are you still working on this? Fingers crossed!

**Comment by petrujenac** [comment]
It doesn't work anymore.

**Comment by Manchmal1** [comment]
Was habe ich falsch gemacht wenn ich fragen darf bitte

**Comment by petrujenac** [comment]
Can you add this list of channels please? https://thedaddy.to/24-7-channels.php

**Comment by DerVollhorst** [comment]
What type of Player should I use? I tried as u mentioned VLC/Mplayer... but the streams are Crashing after 10 minutes and i have to restart the streams (Set Up: Win 11). Do you know what causes these Issue? On Android TV/Fire TV the streams are Not working (with VLC installed). Hope you still developing this addon. Its the only Sports addon that is realy working. Thank you for the development.

**Comment by DryKillLogic** [comment]
The addon is no longer available until further notice.

**Comment by TwilightMercy** [comment]
> The addon is no longer available until further notice.

What is the reason?

**Comment by sekkiaman** [comment]
Is there any possibility to bring it back?

**Comment by THEGUYONGIT1263** [comment]
Please bring it back

**Comment by 0xEleven** [comment]
> Thank you very much for this addon! Finally a decent addon for sports on stremio! I really appreciate your work! Where can I upvote it, as I couldn't find a sub on reddit about it. Can you add this list of channels please? https://thedaddy.to/24-7-channels.php

I was not aware of this list, we need it in streamio

**Comment by thedragon40** [comment]
Is there still no news about the addon? Nothing new?

**Comment by 0xEleven** [comment]
No news but I'd advice you to install media fusion elfhosted addon and configure it, also try udptv and usatv addons

**Comment by thedragon40** [comment]
I have tried them, but to watch sports in Spanish, they don’t work for me because I need to watch specific channels that this addon did have.

**Comment by 0xEleven** [comment]
You can discord me :@0x11_ I will hoom you up with a good iptv service, cheap, no buffering, 60k channels, epg available, vod and tv series

**Comment by Manchmal1** [comment]
Ok  gerne 
Was heißt günstig

**Comment by emaschi5** [comment]
or you can use the OMG tv plus, soon will be out with come cool feature, https://github.com/mccoy88f/OMG-Plus-TV-Stremio-Addon Leave a star and wait for the new version, you can paste a script that create an m3u list, this it took 1 hour.
 https://paste.ee/r/9rKjBggu/0

you'll have all the world sport, except for cricket and other minor sport.

On OMG plus when the new version will come out you need to add the paste.ee as script, download it and run it and use the link provided in the first row, 
if the channel doesn't work you need to use a mediaflow proxy

**Comment by THEGUYONGIT1263** [comment]
> or you can use the OMG tv plus, soon will be out with come cool feature, https://github.com/mccoy88f/OMG-Plus-TV-Stremio-Addon Leave a star and wait for the new version, you can paste a script that create an m3u list, this it took 1 hour. https://paste.ee/r/9rKjBggu/0
> 
> you'll have all the world sport, except for cricket and other minor sport.
> 
> On OMG plus when the new version will come out you need to add the paste.ee as script, download it and run it and use the link provided in the first row, if the channel doesn't work you need to use a mediaflow proxy

Can I please have some help with this?
