### ISSUE TITLE
ℋ ✨ MAX TV ✨ 󠁴󠁭󠁢󠁿  Ỵ

### ISSUE THREAD

**Issue by mik25** [danamag/stremio-addons-list#72]
### Addon Manifest URL

https://2maxtv2.surge.sh/manifest.json

### Addon Description

Mixed World IPTV Streams

### Choose Labels

- [ ] anime
- [ ] asian drama
- [ ] bollywood
- [ ] cartoons
- [ ] debrid support
- [ ] http streams
- [X] live tv
- [ ] metadata
- [ ] misc
- [ ] movies
- [ ] music
- [ ] nsfw
- [ ] podcasts
- [ ] radios
- [ ] subtitles
- [ ] torrents
- [ ] tv shows
- [ ] video games

**Comment by nouahenri** [comment]
Can you add the list of VIP African TV channels. thank you so much

**Comment by mik25** [comment]
done

**Comment by mounirch77** [comment]
Plz add netherland en spain en arab chanel en beinsport arab .thanks

**Comment by nouahenri** [comment]
> done

Thanks you but all the African live TV channels you added , don't work ...Moreover, the list is not complete, unlike the list you previously named AFRICA VIP . Thanks you to fix it

**Comment by mik25** [comment]
the african channels work , tested on desktop and android tv , the issue is with you

**Comment by mik25** [comment]
netherlands and spain are both in euro tv addon

**Comment by nouahenri** [comment]
> the african channels work , tested on desktop and android tv , the issue is with you

I tested it on Android TV because I have a XIAOMI TV STICK connected to my TV... I have also stremio installed on my laptop...I tested the African channels on the both devices and it doesn't work .. I will try again..thanks

**Comment by nouahenri** [comment]
> the african channels work , tested on desktop and android tv , the issue is with you

These are the error message I get on my laptop and android TV 
![screenshot error stremio](https://user-images.githubusercontent.com/83022671/202916627-0c86b68b-2661-4922-b0ac-73b12f47ce85.jpg)
![IMG_20221120_172317](https://user-images.githubusercontent.com/83022671/202916628-eb75bb65-8d09-47d0-9473-a1f907b6f130.jpg)
![IMG_20221120_172307](https://user-images.githubusercontent.com/83022671/202916634-f24b5e0f-1948-4b9c-8ad2-8f50339af09a.jpg)
![IMG_20221120_172253](https://user-images.githubusercontent.com/83022671/202916636-41a027d8-f6e5-417d-88e0-0d37f6207691.jpg)
![IMG_20221120_172205](https://user-images.githubusercontent.com/83022671/202916638-fceea8ad-ba8c-484e-a7e4-2bddbd0cce92.jpg)

**Comment by mounirch77** [comment]
> netherlands and spain are both in euro tv addon

Ok thanks , arab en beinsport arab ??

**Comment by Vouvas** [comment]
Hello! Can you add greek channels cosmote sport and nova sport please? Thanks a lot

**Comment by mik25** [comment]
that channel may be down re africa i can't update the whole addon for 1 stream
arab and bein arab are also available i another addon 
cosmote and nova perhaps on next update

**Comment by nouahenri** [comment]
Ok no probs.. thanks you for all

**Comment by nouahenri** [comment]
> that channel may be down re africa i can't update the whole addon for 1 stream arab and bein arab are also available i another addon cosmote and nova perhaps on next update

Please for the next update of the add-on , can you add in the Africa's category ,  the TV Channels NCI, A+ IVOIRE , Life TV , TV3 all from Cote d'Ivoire ( Ivory coast) and all TRACE's TV CHANNELS . THANKS YOU.

**Comment by mounirch77** [comment]
yes that's right, but the arabic and beninsport in other addons doesn't work that freezes every 10 minutes, but your addons are the best. thanks

**Comment by Vouvas** [comment]
Also one last request, if it's possible to add https://antenna.gr/fifaworldcup2022live (greek world cup)

**Comment by richnyc** [comment]
USA ABC New York actually steaming ABC LA. Needs to have ABC NY

**Comment by richnyc** [comment]
Anyway to add USA channels of MSG, SNY, YES, WPIX NY networks?

**Comment by mounirch77** [comment]
Iit would be nice if you also do morocco and beninsport arab a separate folder, it would be easy for us to zap.thanks

**Comment by T0mP0lefka** [comment]
![1](https://user-images.githubusercontent.com/121064714/208537375-f82ca1ee-c5bf-4816-be75-b4559fa03d4b.png)

Thanks

**Comment by calvino24** [comment]
Thanks a lot for your work !!.
Out of curiosité, could you explain to me how this works ? I mean, all other IPTV add on needs a M3U url or subscription, why is this one free, and working "out of the box" ?
Also, some channels do not seem to work on my phone, while they are totally fine on my computer. Any idea why ?
Thanks again :)

**Comment by challou77** [comment]
please add the dutch Chanel. thanks

**Comment by dewalddejongh** [comment]
Thanks a lot for your work!!

Having the same problems as @nouahenri. None of the SuperSport channels working at the moment also tried different random African channels, none seems to be working at all. Also tried it on Mobile, Desktop, and Android TV I get the same playback error. 

Can you please have a look at this?

**Comment by freestreamEU** [comment]
![Stremio Belgium channel](https://user-images.githubusercontent.com/122747863/213014865-4fed819a-a369-40ef-ba98-2a12498c18dc.png)
![Capture d’écran 2023-01-15 à 19 55 38](https://user-images.githubusercontent.com/122747863/213015003-a18dec17-8b17-4474-ab56-2289a939f31b.png)


NOT WORKING 

Thank's for the great work

**Comment by acbro21** [comment]
Thanks a lot for your work
Having problems with USA channels,looks like none of them are working.
Thanks again!

**Comment by freestreamEU** [comment]
Thank's for the last time for fixing the problem 
But again it's not working for French HD and Belgium channels.
Could you guys fix it?  
Thank's in advance.
![](https://user-images.githubusercontent.com/122747863/213015003-a18dec17-8b17-4474-ab56-2289a939f31b.png)![image](https://user-images.githubusercontent.com/122747863/220072349-8dc09f2c-8fa3-413f-af67-da91d5f9de8a.png)

**Comment by Kurrico** [comment]
Can you add the list of VIP Portuguese TV channels. thank you so much

**Comment by KumaMechaSama** [comment]
Hello, before I comment, I want to thank warmly, the person or persons who work on this addon, so, thank you very much!

Thank you also for following the updates and trying to do the best for the general improvement.

Now, I come to my request:

Country:

FRANCE

Specific request:

Please,

Put back "Prime" concerning the broadcasting of football (league 1).
Indeed, before the last big update, it was possible (sometimes yes, sometimes no) to watch "Amazon Prime" during live football matches.
Unfortunately, since the v22.0.1 update this is no longer possible, these dedicated channels have disappeared from the French offer.

So, if you can integrate them again, you will make many happy!

Thank you for taking the time to read my request, and I hope that you will be able to satisfy it.

**Comment by freestreamEU** [comment]
Thank's for the last time for fixing the problem
But again 3 weeks later it's not working for French HD and Belgium channels.
Could you guys fix it?
Thank's in advance.
![image](https://user-images.githubusercontent.com/122747863/224595034-3bd70df8-0557-41b0-83d1-7fdf7bd6233f.png)
![image](https://user-images.githubusercontent.com/122747863/224595076-360b9470-dd40-4bc6-bbf3-1cc85b09a6d9.png)

**Comment by KumaMechaSama** [comment]
> Thank's for the last time for fixing the problem But again 3 weeks later it's not working for French HD and Belgium channels. It's seems Maxtv addon is not working no channels available. Could you guys fix it? Thank's in advance. ![image](https://user-images.githubusercontent.com/122747863/224595034-3bd70df8-0557-41b0-83d1-7fdf7bd6233f.png) ![image](https://user-images.githubusercontent.com/122747863/224595076-360b9470-dd40-4bc6-bbf3-1cc85b09a6d9.png)

**Comment by KumaMechaSama** [comment]
I confirm and add that from France, none of the channels of all countries, do not work anymore.

I hope to be able to enjoy it very soon, thank you

**Comment by challou77** [comment]
hi are you going to restore those channels? or has the streaming ended.thanks
