### ISSUE TITLE
Google drive addon

### ISSUE THREAD

**Issue by preetstyle** [danamag/stremio-addons-list#723]
### Addon Manifest URL

https://gdrivereborn.sooryasoorya252gmail.workers.dev/manifest.json

### Language of Content

Multilingual (Default)

### Choose Labels

- [ ] anime
- [X] asian drama
- [X] bollywood
- [ ] cartoons
- [ ] debrid support
- [X] http streams
- [ ] live tv
- [ ] metadata
- [ ] misc
- [X] movies
- [ ] music
- [ ] nsfw
- [ ] podcasts
- [ ] radios
- [ ] subtitles
- [ ] torrents
- [X] tv shows
- [ ] video games

**Comment by sleeyax** [comment]
@preetstyle your addon is down so I can't approve it

Please reopen with a working URL
