### ISSUE TITLE
fmovies site

### ISSUE THREAD

**Issue by Namelessbastard** [danamag/stremio-addons-list#75]
### Addon Manifest URL

https://fmoviesto.site/

### Addon Description

actual fmovies website

### Language of Content

English (en-US)

### Choose Labels

- [ ] anime
- [ ] asian drama
- [ ] bollywood
- [ ] cartoons
- [ ] debrid support
- [ ] http streams
- [ ] live tv
- [ ] metadata
- [ ] misc
- [X] movies
- [ ] music
- [ ] nsfw
- [ ] podcasts
- [ ] radios
- [ ] subtitles
- [ ] torrents
- [X] tv shows
- [ ] video games

**Comment by danamag** [comment]
i don't know what that is, but it's not a new addon, so i'm closing this
