### ISSUE TITLE
pochita

### ISSUE THREAD

**Issue by pochitakun** [danamag/stremio-addons-list#76]
### Addon Manifest URL

pochitalol@proton.me

### Language of Content

Multilingual (Default)

### Choose Labels

- [x] anime
- [ ] asian drama
- [ ] bollywood
- [ ] cartoons
- [ ] debrid support
- [ ] http streams
- [ ] live tv
- [ ] metadata
- [ ] misc
- [ ] movies
- [ ] music
- [ ] nsfw
- [ ] podcasts
- [ ] radios
- [ ] subtitles
- [ ] torrents
- [ ] tv shows
- [ ] video games

**Comment by danamag** [comment]
i don't know what that is, but it's not a new addon, so i'm closing this
