### ISSUE TITLE
poch

### ISSUE THREAD

**Issue by pochitakun** [danamag/stremio-addons-list#77]
### Addon Manifest URL

pochitalol@proton.me

### Choose Labels

- [X] anime
- [ ] asian drama
- [ ] bollywood
- [ ] cartoons
- [ ] debrid support
- [ ] http streams
- [X] live tv
- [ ] metadata
- [ ] misc
- [X] movies
- [ ] music
- [ ] nsfw
- [ ] podcasts
- [ ] radios
- [X] subtitles
- [X] torrents
- [X] tv shows
- [ ] video games

**Comment by danamag** [comment]
i don't know what that is, but it's not a new addon, so i'm closing this
