### ISSUE TITLE
ℋ  🏆 WORLD CUP SPORTS 🏆 󠁴󠁭󠁢󠁿  Ỵ

### ISSUE THREAD

**Issue by mik25** [danamag/stremio-addons-list#81]
### Addon Manifest URL

https://worlcup.surge.sh/manifest.json

### Addon Description

World Sports streams

### Choose Labels

- [ ] anime
- [ ] asian drama
- [ ] bollywood
- [ ] cartoons
- [ ] debrid support
- [ ] http streams
- [X] live tv
- [ ] metadata
- [ ] misc
- [ ] movies
- [ ] music
- [ ] nsfw
- [ ] podcasts
- [ ] radios
- [ ] subtitles
- [ ] torrents
- [ ] tv shows
- [ ] video games

**Comment by the-nos4a2** [comment]
What are the VIP Links?

**Comment by mik25** [comment]
they are just FHD links

**Comment by the-nos4a2** [comment]
> they are just FHD links

But I can't access them, like I can't access Sport TV 1 VIP
