### ISSUE TITLE
Addon Namehttps://dmwalking.surge.sh/manifest.json

### ISSUE THREAD

**Issue by Elcaponi** [danamag/stremio-addons-list#83]
### Addon Manifest URL

https://dmwalking.surge.sh/manifest.json

### Choose Labels

- [ ] anime
- [ ] asian drama
- [ ] bollywood
- [ ] cartoons
- [ ] debrid support
- [ ] http streams
- [ ] live tv
- [ ] metadata
- [ ] misc
- [ ] movies
- [ ] music
- [ ] nsfw
- [ ] podcasts
- [ ] radios
- [ ] subtitles
- [ ] torrents
- [ ] tv shows
- [ ] video games

**Comment by danamag** [comment]
i don't know what that is, but it's not a new addon, so i'm closing this
