### ISSUE TITLE
YouTube 

### ISSUE THREAD

**Issue by MohamedMoataz31** [danamag/stremio-addons-list#85]
### Addon Manifest URL

https://m.youtube.com/manifest.json

### Language of Content

English (en-GB)

### Choose Labels

- [ ] anime
- [ ] asian drama
- [ ] bollywood
- [ ] cartoons
- [ ] debrid support
- [x] http streams
- [ ] live tv
- [ ] metadata
- [ ] misc
- [x] movies
- [ ] music
- [ ] nsfw
- [ ] podcasts
- [ ] radios
- [ ] subtitles
- [ ] torrents
- [x] tv shows
- [ ] video games

**Comment by MohamedMoataz31** [comment]
> ### Addon Manifest URL
> https://m.youtube.com//manifest.json
> 
> ### Addon Description
> _No response_
> 
> ### Language of Content
> English (en-GB)
> 
> ### Choose Labels
> * [ ]  anime
> * [ ]  asian drama
> * [ ]  bollywood
> * [ ]  cartoons
> * [ ]  debrid support
> * [ ]  http streams
> * [ ]  live tv
> * [ ]  metadata
> * [ ]  misc
> * [ ]  movies
> * [ ]  music
> * [x]  nsfw
> * [ ]  podcasts
> * [ ]  radios
> * [ ]  subtitles
> * [ ]  torrents
> * [ ]  tv shows
> * [ ]  video games

**Comment by danamag** [comment]
i don't know what that is, but it's not a new addon, so i'm closing this
