### ISSUE TITLE
Stremify Music Catalog

### ISSUE THREAD

**Issue by rleroi** [danamag/stremio-addons-list#86]
### Addon Manifest URL

https://7a82163c306e-stremify.baby-beamup.club/manifest.json

### Addon Description

Provides Spotify music catalogs to Stremio. Includes YouTube Music sources. Allows searching playlists and tracks.

### Language of Content

English (en-US)

### Choose Labels

- [ ] anime
- [ ] asian drama
- [ ] bollywood
- [ ] cartoons
- [ ] debrid support
- [ ] http streams
- [ ] live tv
- [x] metadata
- [ ] misc
- [ ] movies
- [X] music
- [ ] nsfw
- [ ] podcasts
- [ ] radios
- [ ] subtitles
- [ ] torrents
- [ ] tv shows
- [ ] video games

**Comment by MrC001** [comment]
No longer works.  No links, no connects.
