### ISSUE TITLE
🧟‍ DMW TV AR 🧟‍

### ISSUE THREAD

**Issue by mik25** [danamag/stremio-addons-list#88]
### Addon Manifest URL

https://dmwalkingar.surge.sh/manifest.json

### Addon Description

اختبار ADDON للتلفزيون العربي المباشر و VOD

### Language of Content

None

### Choose Labels

- [ ] anime
- [ ] asian drama
- [ ] bollywood
- [ ] cartoons
- [ ] debrid support
- [ ] http streams
- [X] live tv
- [ ] metadata
- [ ] misc
- [ ] movies
- [ ] music
- [ ] nsfw
- [ ] podcasts
- [ ] radios
- [ ] subtitles
- [ ] torrents
- [ ] tv shows
- [ ] video games

**Comment by challou77** [comment]
please add the arab chanel .thanks
