### ISSUE TITLE
Anime Kamyroll (Crunchyroll streams) [Public Beta]

### ISSUE THREAD

**Issue by rleroi** [danamag/stremio-addons-list#89]
### Addon Manifest URL

https://7a82163c306e-kamyroll.baby-beamup.club/manifest.json

### Addon Description

Crunchyroll anime HTTP streams with subtitles. Requires Anime Kitsu Addon.

![image](https://user-images.githubusercontent.com/6817390/209038371-e5ccfae9-f121-435f-8fd6-7b1b987cc594.png)

Source: https://github.com/rleroi/stremio-kamyroll-addon

### Language of Content

Multilingual (Default)

### Choose Labels

- [X] anime
- [ ] asian drama
- [ ] bollywood
- [X] cartoons
- [ ] debrid support
- [X] http streams
- [ ] live tv
- [ ] metadata
- [ ] misc
- [ ] movies
- [ ] music
- [ ] nsfw
- [ ] podcasts
- [ ] radios
- [X] subtitles
- [ ] torrents
- [ ] tv shows
- [ ] video games

**Comment by bakaprince** [comment]
Where's the apk

**Comment by lalalasupa0** [comment]
Can't found it in the addons list...
