### ISSUE TITLE
Addon Name

### ISSUE THREAD

**Issue by ewat06** [danamag/stremio-addons-list#90]
### Addon Manifest URL

https://pinayflix.tv/manifest.json

### Addon Description

we

### Language of Content

None

### Choose Labels

- [ ] anime
- [ ] asian drama
- [ ] bollywood
- [ ] cartoons
- [ ] debrid support
- [X] http streams
- [ ] live tv
- [ ] metadata
- [ ] misc
- [ ] movies
- [ ] music
- [ ] nsfw
- [ ] podcasts
- [ ] radios
- [ ] subtitles
- [ ] torrents
- [ ] tv shows
- [ ] video games

**Comment by danamag** [comment]
i don't know what that is, but it's not a new addon, so i'm closing this
