### ISSUE TITLE
Wiflix

### ISSUE THREAD

**Issue by jean431** [danamag/stremio-addons-list#91]
### Addon Manifest URL

https://www.wiflix-stream.fr/

### Language of Content

None

### Choose Labels

- [X] anime
- [ ] asian drama
- [ ] bollywood
- [ ] cartoons
- [ ] debrid support
- [ ] http streams
- [ ] live tv
- [ ] metadata
- [ ] misc
- [X] movies
- [ ] music
- [ ] nsfw
- [ ] podcasts
- [ ] radios
- [ ] subtitles
- [X] torrents
- [ ] tv shows
- [ ] video games

**Comment by danamag** [comment]
i don't know what that is, but it's not a new addon, so i'm closing this
