### ISSUE TITLE
Addon Name

### ISSUE THREAD

**Issue by rachid63rachid** [danamag/stremio-addons-list#93]
### Addon Manifest URL

https:// peario.xyz

### Language of Content

French (fr-FR)

### Choose Labels

- [ ] anime
- [ ] asian drama
- [ ] bollywood
- [ ] cartoons
- [X] debrid support
- [X] http streams
- [X] live tv
- [X] metadata
- [X] misc
- [X] movies
- [X] music
- [ ] nsfw
- [ ] podcasts
- [X] radios
- [ ] subtitles
- [X] torrents
- [ ] tv shows
- [ ] video games

**Comment by danamag** [comment]
i don't know what this is, but it's not an addon, closing it
