### ISSUE TITLE
Juan

### ISSUE THREAD

**Issue by amineMS0x** [danamag/stremio-addons-list#94]
### Addon Manifest URL

http://juan.stremioaddons.space/stremio/v1

### Language of Content

English (en-NZ)

### Choose Labels

- [ ] anime
- [ ] asian drama
- [ ] bollywood
- [ ] cartoons
- [ ] debrid support
- [X] http streams
- [ ] live tv
- [ ] metadata
- [ ] misc
- [ ] movies
- [ ] music
- [ ] nsfw
- [ ] podcasts
- [ ] radios
- [ ] subtitles
- [ ] torrents
- [ ] tv shows
- [ ] video games

**Comment by danamag** [comment]
that addon uses the old addon sdk, this project only supports the new addon sdk, links should end with /manifest.json
