### ISSUE TITLE
RARBG Torrents

### ISSUE THREAD

**Issue by marcostux06** [danamag/stremio-addons-list#96]
### Addon Manifest URL

https://app.strem.io/shell-v4.4/#/addons/community/all?addon=https%3A%2F%2Frarbg.addon.unlimited-fun.xyz%2Fmanifest.json

### Addon Description
Watch Movies and Series from RARBG 

### Language of Content

Multi

### Choose Labels

- [ ] anime
- [ ] asian drama
- [ ] bollywood
- [ ] cartoons
- [ ] debrid support
- [ ] http streams
- [ ] live tv
- [ ] metadata
- [ ] misc
- [X] movies
- [ ] music
- [ ] nsfw
- [ ] podcasts
- [ ] radios
- [ ] subtitles
- [ ] torrents
- [ ] tv shows
- [ ] video games

**Comment by danamag** [comment]
this is not the way to submit working addons, they need to end with /manifest.json
