### ISSUE TITLE
Community OpenSubtitles

### ISSUE THREAD

**Issue by marcostux06** [danamag/stremio-addons-list#98]
### Addon Manifest URL

https://app.strem.io/shell-v4.4/#/addons/community/all?addon=https%3A%2F%2F32d94ecc2689-stremio-addon-opensubtitles.baby-beamup.club%2Fspa%2Fmanifest.json

### Addon Description

Community add-on for subtitles from OpenSubtitles 

### Language of Content

Multilingual (Default)

### Choose Labels

- [ ] anime
- [ ] asian drama
- [ ] bollywood
- [ ] cartoons
- [ ] debrid support
- [ ] http streams
- [ ] live tv
- [ ] metadata
- [ ] misc
- [ ] movies
- [ ] music
- [ ] nsfw
- [ ] podcasts
- [ ] radios
- [X] subtitles
- [ ] torrents
- [ ] tv shows
- [ ] video games

**Comment by danamag** [comment]
this is not the way to submit working addons, they need to end with /manifest.json
