### ISSUE TITLE
Séptimo Arte

### ISSUE THREAD

**Issue by marcostux06** [danamag/stremio-addons-list#99]
### Addon Manifest URL

https://app.strem.io/shell-v4.4/#/addons/community/all?addon=https%3A%2F%2Fseptimo-arte-addon-qfpm3t60o.vercel.app%2Fmanifest.json

### Addon Description

Películas y series en español latino, también estrenos de cine en español latino

### Language of Content

Spanish; Castilian (es-MX)

### Choose Labels

- [ ] anime
- [ ] asian drama
- [ ] bollywood
- [ ] cartoons
- [ ] debrid support
- [ ] http streams
- [ ] live tv
- [ ] metadata
- [ ] misc
- [X] movies
- [ ] music
- [ ] nsfw
- [ ] podcasts
- [ ] radios
- [ ] subtitles
- [ ] torrents
- [ ] tv shows
- [ ] video games

**Comment by danamag** [comment]
this is not the way to submit working addons, they need to end with /manifest.json
